lumibot/tools/pandas.py
In the pandas `tools` helper, the method `day_deduplicate` is using iterations to create a final dataframe without duplicate dates. Proposing using groupby which is vectorized.
Checked the original vs. the groupby function with log files and trace_stats. Results are identical.
=> Pandas iteration to groupby

.gitignore, lumibot/__init__.py, lumibot/data_sources/yahoo.py, lumibot/tools/helpers.py, lumibot/tools/indicators.py
A few areas in yfinance that we could pick up some speed with. Results in backtesting match master using diversification. 
Commit message: 
- Optimizing adding start and end dates, and threading, download multiple stocks all at once.
Downloading reduces time about 2 seconds for from 11.5 to 9.5 on average for one year backtest with five tickers.
When downloading in bulk, not using max, yf will return dates not including the last. To compensate, seven days were added and then refiltered.
For the historical datetime index, the latest index will be pickled locally, and retrieved for subsequent test, and saved each test. This will illiminate the need for a max download with all ohlc for each backtest. Also dropped the ohlcv info right away and managed the datetimes in a list/set for …
=> yfinance optimize

lumibot/tests/test_strategies.py
This accounts for the one day lag introduced by Yahoo Finance when filtering for start date instead of max.
=> Adjust test valid values for the Momentum Test

lumibot/strategies/strategy_executor.py
In `strategy_executor` lost the `**self.strategy.kwargs` parameter. This caused kwargs to not be loaded in `strategy.initialize`.
Added in new parameter now as `**self.strategy.parameters`. Now all keyword arguments running in strategies.
=> When strategy parameters for live update implemented, lost kwargs argument

lumibot/brokers/interactive_brokers.py
Interactive Brokers will return positions with zero quantity. This carries through to Lumibot and `self.get_positions` will return assets with `0` quantity, which can lead to errors in the user bot if `len(self.get_positions)` is used.
List comprehension added to IB to remove positions with '0' quantity.
Black formatter did some minor formatting.
2nd commit: 
In `_parse_broker_order` in InteractiveBrokers, the existing incorrect code is trying to use `DATE_MAP` using IB code eg: `OPT`. Needs to use lumibot's `option` which is take from the `TYPE_MAP` dictionary.
=> Code correction: IB Positions returning 0 quantity.

.gitignore, lumibot/entities/order.py, lumibot/entities/trading_fee.py, requirements.txt, requirements_dev.txt, setup.cfg, tests/test_alpaca.py, tests/test_ccxt.py, tests/test_order.py, tests/test_tradingfee.py
Main purpose is to add a new function to lumibot.entities.order and provide the testing.  As per our agreement, I also added some additional tests to TradingFee to incrementally improve coverage in some other area of the repository.
---
To run coverage:
```
- Install requirements file:
pip install -r requirements_dev.txt
- 3 step command to generate a full coverage report
coverage run
coverage report
coverage html
- open the generated ".coverage.html_report/index.html" file in your browser
```
You will get a coverage report in the terminal that looks like:
And the same data in a nice HTML version:
---
```diff
+ New code is all Green -- Fully Covered!
```
---
Sorted by the coverage column!
We now have a fully covered module!! 🎉 🥳
=> Adding order.get_filled_price() and enabling pytest coverage

lumibot/__init__.py, requirements.txt, setup.py
Using directories pointed to with the appdirs module instead of using the pip-install area for caching.
=> Updated caching directory to use system cache areas 

lumibot/data_sources/interactive_brokers_data.py
datetime index where minutes are being repeated.
_Should show_
Red box: min=43,44
Yellow Box: min=45,46
Green Box: min=47,48,49
=> Bug: With updated Pandas, IBKR data is being returned with invalid index

lumibot/brokers/broker.py, lumibot/entities/order.py, tests/test_order.py
Filled and Cancelled orders are getting re-cancelled every iteration because the orders no longer map properly to the list of InteractiveBroker orders.
=> Fixing IBKR Live Trading runs continuously re-canceling 

lumibot/backtesting/polygon_backtesting.py, lumibot/entities/data.py, lumibot/entities/order.py, setup.py
basically the issue was that if we got day data first, then the data store would never attempt to get minute data. that has now been changed so that we always try to keep the minimum timestep in the data store
=> fixed edge case where we first get day data, then request minute data

lumibot/backtesting/polygon_backtesting.py, lumibot/data_sources/alpaca_data.py, lumibot/data_sources/data_source.py, lumibot/entities/bars.py, lumibot/entities/data.py, lumibot/strategies/strategy.py
Issue during Live Trading:
- IBKR couldn't return 10days worth of history in 1m bars. 
- Need to use ```timestep='10 minutes'``` as an input
- BackTest doesn't handle "10 minutes" as a valid timestep
=> BackTest Multi Min TimeStep

.gitignore, lumibot/brokers/__init__.py, lumibot/brokers/tradier.py, lumibot/data_sources/__init__.py, lumibot/data_sources/tradier_data.py, setup.cfg, tests/__init__.py, tests/backtest/test_example_strategies.py, tests/test_tradier.py
Tradier DataSource working with get_last_price() for a real stock.  Unittest implemented and fully plumbed in lumibot, but these are now marked as an "apitest" which GitHub CI/CD pipelines will skip to avoid hitting any kind of rate limits or requiring separate Unit Test Tradier accounts.
=> Tradier data source

lumibot/brokers/broker.py, lumibot/brokers/tradier.py, lumibot/entities/asset.py, lumibot/entities/order.py, lumibot/strategies/strategy_executor.py, lumibot/tools/__init__.py, lumibot/tools/helpers.py, lumibot/tools/indicators.py, lumibot/trading_builtins/__init__.py, lumibot/trading_builtins/custom_stream.py, lumibot/trading_builtins/safe_list.py, setup.cfg, tests/test_asset.py, tests/test_order.py, tests/test_tradier.py
This is a big update that implements a Polling feature for handling Order Status Updates.  All current brokers (Alpaca, IBKR, etc) use websocket streaming to send status changes as they happen.  However, Tradier does not support websocket streaming on their paper accounts (Live accounts only).  To support his new methodology, a new CustomStream class has been created that will process polling results in a manner similar to how the websocket streaming works.  The main difference for the Polling process now is that the PollingSteam class itself will look for user issued poll events and if none are found after a timeout period, it will automatically do the polling itself.  This allows the user to "poke" the broker for more frequent updates if they desire.
This update is fairly complicated …
=> Tradier polling

lumibot/strategies/_strategy.py, lumibot/tools/indicators.py
Currently, the show_plot flag is ignored by the indicators.html file.  This file is opened in a browser every time.
The " fig.write_html(plot_file_html, auto_open=show_plot)" invocation to create the file references the flag, but since it was not properly passed along the call tree, it always defaulted to "True."
This pull request corrects this behavior.
=> Correct show_plot to also control the indicator.html file display in a browser.

lumibot/backtesting/__init__.py, lumibot/backtesting/ccxt_backtesting.py, lumibot/data_sources/__init__.py, lumibot/data_sources/ccxt_backtesting_data.py, lumibot/example_strategies/ccxt_backtesting_example.py, lumibot/strategies/_strategy.py, lumibot/tools/__init__.py, lumibot/tools/ccxt_data_store.py, lumibot/tools/indicators.py, requirements.txt, setup.py, tests/backtest/test_example_strategies.py, tests/test_ccxt_store.py
● ccxt data cache :  lumibot/tools/ccxt_data_store.py
- This module used duckdb to cache the ccxt data, see the in-source documentation for details.
- Used when backtesting CCXT.
● ccxt data cache test module: tests/test_ccxt_store.py
● ccxt backtesting data source : lumibot/data_sources/ccxt_backtesting_data.py
- This module is similar to the structure of yahoo_data.py.
- The ccxt data cache module is used here.
● ccxt backtesting : lumibot/backtesting/ccxt_backtesting.py
- This module is similar to the structure of yahoo_backtesting.py.
● ccxt backtesting example : lumibot/example_strategies/ccxt_backtesting_example.py
- binance, bitmex backtesting example
- Use `ccxt backtesting data source` as the benchmark data source.
● _strategy.py, ccxt.py  modified for ccxt backtesting
=> ccxt backtest and ccxt data cache, ccxt backtest example upload, _strategy.py, ccxt.py modified for ccxt backtest

lumibot/strategies/strategy.py, lumibot/tools/polygon_helper.py, tests/test_polygon_helper.py
For tickers that have missing bars (because there weren't any orders filled those trading days) there are repeated calls to Polygon to (re-)fetch those "missing" dates.  This fix adds "empty" (i.e. all NaN values) rows for those days where Polygon returned no data.  That way when polygon_helper.get_price_data_from_polygon is called for bars which are known to be missing we don't call Polygon again for those days.
As part of this refactoring I dropped the "don't write feather cache file when contents duplicated".  With this change that (a call to update_cache without changes) shouldn't happen.  There is checking and logging for this occurence.
A couple tweaks accumulated are:
1) Add timestamp conversion in data.get_bars because in some cases the type of the column isn't correct.
2) Tweaks …
=> Fix repeated bar fetches from Polygon along with some minor nits.

lumibot/data_sources/pandas_data.py, lumibot/tools/polygon_helper.py
A fix for https://github.com/Lumiwealth/lumibot/issues/390.
=> Keep track of what the split history is for each stock symbol's cache feather file.  Invalidate the (i.e. force redownload) when the splits change.

lumibot/brokers/ccxt.py
In ccxt, the price precision returned by Binance is different from other exchanges, which leads to limit orders rounding off decimals, and this always causes issues with the prices.
Binance market data like:
```json
{
'precision': {'amount': 5, 'price': 2, 'cost': None, 'base': 8, 'quote': 8}
}
```
=> Fix ccxt binance price precision

lumibot/data_sources/data_source.py, lumibot/data_sources/data_source_backtesting.py, lumibot/strategies/strategy.py
Allows the user to optionally adjust for delayed data timestamps with a new flag to pass to the get_datetime(adjust_for_delay=True) calls.
=> get_datetime: added in optional delay accounting

lumibot/tools/ccxt_data_store.py
When running the code with crypto currencies, the table is created with a restrictive column type which does not play nice with the backtesting_broker. 
This change should address the above issue and ensure that the data will work with the backtesting_broker.
=> :hammer:: Fix column with wrong types

lumibot/tools/polygon_helper.py
Fix for https://github.com/Lumiwealth/lumibot/issues/401.  Check for whether stock splits have changed for options when validating Polygon cache.
This turned out to be trivial since the logic is identical to what was done for stocks (https://github.com/Lumiwealth/lumibot/issues/390).
=> Invalidate Polygon cache for options of a stock when its splits have changed.

lumibot/data_sources/yahoo_data.py, lumibot/tools/indicators.py, lumibot/tools/yahoo_helper.py, setup.py
Updated Yahoo backtesting data to support 1 minute and 15 minute intervals.  Yahoo supports 1 minute intervals for past 7 days and 15 minute intervals for past 60 days.
In setup.py, there is a dependency on scipy==1.10.1.  That version appears to have been yanked.  I set to 1.13.0 but please change is that is not correct.
=> Support Yahoo data at 1 minute and 15 minute intervals

lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py
If you provide a risk_free_rate to backtest() strategy class method it does not set the risk_free_rate instance variable, always tries to get data from yahoo finance.
=> Fixed risk_free_rate bug

lumibot/strategies/_strategy.py, lumibot/traders/trader.py, tests/backtest/test_polygon.py, tests/backtest/test_yahoo.py
An anomalous behaviour concerning the saving of a tearsheet file with a custom name was fixed. Previously, even if a custom name was entered when launching a backtest, the file name was not used.
=> Fix custom tearsheet name

lumibot/backtesting/polygon_backtesting.py, lumibot/data_sources/pandas_data.py, requirements.txt, setup.py, tests/backtest/test_polygon.py
At head, `get_historical_prices` always returns None for Polygon data source. The reason is that `get_historical_prices` internally calls [_pull_source_symbol_bars](https://github.com/Lumiwealth/lumibot/blob/96d73cd69f4b0c525e33668b1983b1a001a8059b/lumibot/data_sources/pandas_data.py#L247), which tries to retrieve the data from `self._data_store`. Without updating the data store, above script will always return None. 
Per discussion in https://github.com/Lumiwealth/lumibot/pull/430, this PR merges data_store and pandas_data. It also removes the `update_data_store` argument and simplifies the code logic.
=> Fix get_historical_prices for PolygonDataBacktesting data source

lumibot/entities/data.py, tests/backtest/test_polygon.py
There are 2 issues if the underlying data source contains `minute` timestep data, and the user calls `get_historical_prices` with `timestep=day`:
1. returns more days than requested
2. includes partial day data from the current day
Consider the following snippet:
```python
prices = data_source.get_historical_prices("AAPL", 2, "minute")
prices = data_source.get_historical_prices("AAPL", 1, "day")
```
=> Fix "day" level historical prices when the data source uses minute bars

lumibot/tools/yahoo_helper.py
When the cache file can't be read because it is corrupted the backtest slows down instead of recovering (which depends on manual intervention after a super slow run).
=> Remove Yahoo data pickle cache file when it can't be read.

lumibot/backtesting/polygon_backtesting.py, tests/backtest/fixtures.py, tests/backtest/test_polygon.py
- Removed duplicate calls to self.get_start_datetime_and_ts_unit within _update_pandas_data to prevent exceeding API limits.
- Added unit test to verify correct data handling in Polygon API calls.
=> Fix miscalculated start datetime in _pull_source_symbol_bars

lumibot/strategies/strategy_executor.py, tests/backtest/test_polygon.py
When the strategy is intra-day (with sleeptime < 1D), the strategy executor will run one extra day after the `datetime_end`, which is incorrect. This change adds another `should_continue` check before the market opens, so it respects the `datetime_end` more rigorously.
For example, if the `datetime_end=2024-02-10`, which is a Saturday.
- The behavior at head will try to run the strategy on `2024-02-12` (a Monday). The executor stops at the market close time of `2024-02-12`.
- With this PR, the executor will run all the lifecycle methods on `2024-02-09` (Friday), and then sleep until before the market opens on `2024-02-12`, and stops there
=> Correct date range for intra-day strategy

lumibot/brokers/tradier.py
Tradier orders pulled from the broker are missing the average_fill_price property. This causes order.avg_fill_price and order.get_fil_price() to return 0.0. This PR fixes issue #436 .
=> populate avg_fill_price

lumibot/strategies/_strategy.py, lumibot/traders/trader.py, tests/backtest/test_polygon.py
Since https://github.com/Lumiwealth/lumibot/commit/7d072abd72b1197215cd7e50ae5ad9043d2a36e2, `trader.run_all(save_tearsheet=True)` no longer works, because `tearsheet_file` defaults to empty string (which is not None), and the downstream does not update its value.
This change does the following:
- update a test to make sure `trader.run_all(save_tearsheet=True)` can run without any crash
- update `tearsheet_file=None`
- update downstream (_strategy.py) to handle both empty string and None
Before the change we will get the following error and stack trace:
```
FAILED tests/backtest/test_polygon.py::TestPolygonBacktestFull::test_polygon_restclient - FileNotFoundError: [Errno 2] No such file or directory: ''
lumibot/traders/trader.py:122: in run_all
strat.backtest_analysis( …
```
=> fix empty tearsheet_file for trader.run_all

lumibot/traders/trader.py
This was giving an error when trying to backtest with run_all():
FileNotFoundError: [Errno 2] No such file or directory: ''
=> fix tearsheet_file error when using run_all()

lumibot/brokers/broker.py, lumibot/data_sources/data_source.py, lumibot/data_sources/tradier_data.py, lumibot/strategies/strategy.py, tests/test_data_source.py, tests/test_tradier.py
All options for a given expiration date can have the full greeks, bid/ask, open_interest, etc. calculated in a single efficient execution.
For Tradier and Polygon-Live, all of the greeks for every option can be returned with a single API call.  This is much faster than looping and doing individual get_last_price() + calculate_greeks() calls.
For Polygon-BackTest and IBKR, we will have to continue to do the slow way of repeated queries.  Filtering options included to help speed this step up as well.
=> data_source: added new function get_chain_full_info() 

.github/workflows/cicd.yaml, assets.json, lumibot/backtesting/polygon_backtesting.py, lumibot/tools/polygon_helper.py, tests/backtest/test_example_strategies.py, tests/backtest/test_polygon.py, tests/test_polygon_helper.py
With the new rate limited RESTClient class (PolygonClient) all current and future polygon API calls will be rate limited if needed. This was not done before for list_option_contracts, for example.
This also enables local testing with a free polygon key (works but slow). For local testing with free account you have to add an environment variable called POLYGON_IS_PAID_SUBSCRIPTION=False
NOTE: This is the old PR #452 made from main repo for testing purposes.
=> Better rate limited RESTClient

lumibot/strategies/_strategy.py
Fix Issue #406 which is due to trying to access _backtesting_start when not backtesting.
Also move that big chunk of code into its own method so we can see what's going on.
=> Don't access _strategy._backtesting_start when it isn't set

lumibot/strategies/strategy.py
Process pending orders whenever self.sleep() is called. Off by default as to not break any current strategies. 
Could be useful, for example, after running self.sell_all() to ensure all positions execute before your strategy continues (and potentially opens new positions)
=> process_pending_orders in self.sleep() method

lumibot/tools/polygon_helper.py
Better polygon message, showing REST API call path to better know which plan is needed.
=> Polygon maxretry showpath

lumibot/tools/polygon_helper.py
This is to avoid showing error messages on weekends and holidays during backtesting.
=> Changed logging.error() to logging.debug() when lengh of contact is zero.

lumibot/brokers/interactive_brokers.py
Added max_connection_retries to reconnect function
Removed sleeplen as it is now obsolete
> [!NOTE]
> This feature is in early access. You can enable or disable it in the [Korbit Console](https://app.korbit.ai/settings).
Increase the maximum connection retries to 1000 and remove the sleep delay after reconnecting in the Interactive Brokers broker implementation.
The previous limit of zero retries was insufficient for maintaining a stable connection, leading to frequent disconnections. Increasing the retries to 1000 ensures more robust reconnection attempts. The sleep delay was removed to streamline the reconnection process, as it was deemed unnecessary for ensuring connection stability.
=> Fixed IB reconnect issues

lumibot/strategies/_strategy.py, lumibot/traders/trader.py
> [!NOTE]
Improve backtesting filenames by adding a unique random string to avoid overwriting existing files.
The previous implementation used a timestamp-based filename which could lead to overwriting files if multiple backtests were run within the same second. Adding a random string ensures that each filename is unique, preventing accidental overwrites and data loss.
=> improved backtesting filenames

lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, lumibot/strategies/strategy_executor.py
Implemented strategy.vars dictionary. All variables in it can optionally be backed up/restored through an SQL DB. Useful for when a strategy that is dependant on past variables needs to be restarted/crashes. 
Introduced new strategy initialization flags:
should_backup_variables_to_database-enables the db backing up feature
should_send_summary_to_discord-enables the discord summary functionality (which was enabled by default before)
=> Variable Backing Up/Restoring through a PostgreSQL DB

lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py
Variables in self.vars can now be accessed by self.vars.varname instead of self.vars[varname]
self.should_send_summary_to_discord (added in my DB backup PR) proved to be useless. Now if a discord webhook is available, we send summary to discord.
> [!NOTE]
Refactor `self.vars` from a dictionary to an instance of the `Vars` class to encapsulate variable management within the `_Strategy` class.
This change improves the encapsulation and management of strategy variables, providing a more robust and error-resistant way to handle dynamic attributes. The `Vars` class ensures that attribute access and assignment are handled gracefully, …
=> Changed self.vars syntax and removed should_send_summary_to_discord

lumibot/brokers/broker.py, lumibot/brokers/tradier.py, lumibot/entities/order.py, setup.py, tests/test_tradier.py
> [!NOTE]
Add support for tracking and processing orders with an &quot;error&quot; status in the `lumibot` library.
This change ensures that all orders, including those with errors, are tracked and processed correctly, providing a more comprehensive order management system. This addresses the issue of untracked error orders and improves the robustness of the order handling mechanism.
=> return all orders regardless of the status

lumibot/brokers/alpaca.py, lumibot/entities/order.py, tests/test_order.py
> [!NOTE]
Add support for child orders to the `Order` object to handle OCO, OTO, and Bracket orders.
This change allows for better management and tracking of complex order types by associating child orders with a parent order. This approach simplifies the handling of advanced order types and ensures that related orders are processed together. Additionally, it includes tests to verify the new functionality.
=> added child orders to order object for OCO, OTO, Bracket, etc

lumibot/entities/order.py, lumibot/strategies/strategy.py, setup.py
> [!NOTE]
Extend the default duration for spark charts sent to Discord from 180 days to 1095 days and update the package version to 3.6.1.
The extension to 1095 days provides a longer historical view of portfolio performance, which can be more insightful for users. The version bump reflects this enhancement in the package.
=> longer spark chart

.github/workflows/cicd.yaml, lumibot/backtesting/__init__.py, lumibot/backtesting/backtesting_broker.py, lumibot/backtesting/polygon_backtesting.py, lumibot/backtesting/thetadata_backtesting.py, lumibot/brokers/broker.py, lumibot/brokers/ccxt.py, lumibot/data_sources/pandas_data.py, lumibot/entities/data.py, lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, lumibot/strategies/strategy_executor.py, lumibot/tools/indicators.py, lumibot/tools/polygon_helper.py, lumibot/tools/thetadata_helper.py, requirements.txt, tests/backtest/test_polygon.py, tests/backtest/test_thetadata.py
Major changes:
1. Bring up thetadata feature as datasource for backtesting
2. Back tested with options_condor_martingale strategy and verified its functionality
Small feature changes:
1. Introduced a automatic holiday + weekends detection feature in thetadata_helper.py
When see weekends or holiday, skip streaming data from thetadata. Verified the backtesting speed impact  is minimal 
3. Handled error messages, in skip days, avoid print out any error messages
4. If there is data stream error in normal days, still print out errors as original logic does
5. Thetadata works with NewYork time, but polygon works with UTC time. I added summer vs winter timezone adjustment, to match polygon timestamps
6. subtracted 1 min from thetadata to match with polygon timestamps 
7. thetadata_helper.py Will …
=> Prepare to merge thetadata feature into Lumibot 

lumibot/strategies/_strategy.py
Caused issues after thetadata was merged
> [!NOTE]
This change removes the deprecated `polygon_api_key` and `polygon_has_paid_subscription` options from the `run_backtest` and `backtest` functions. These options are no longer necessary as the functionality is now handled automatically, and the `api_key` parameter should be used instead. This cleanup helps to simplify the code and avoid confusion for users.
=> re removed deprecated polygon options

lumibot/strategies/strategy.py
Enabled get_quote for strategy to use. 
Removed slowdown backtesting issue
Enable the use of a specific quote source for options in the strategy and remove the database backup functionality during backtesting.
The change allows the strategy to fetch quotes from a dedicated option source when dealing with options, improving accuracy and flexibility. The removal of database backup during backtesting is to enhance performance by avoiding unnecessary operations, as backtesting does not require persistent storage of variables.
=> Enabled big/ask for strategy to use. Removed slowdown backtesting

lumibot/brokers/broker.py, lumibot/brokers/tradier.py, lumibot/entities/asset.py, lumibot/entities/order.py, lumibot/strategies/strategy.py, lumibot/tools/helpers.py, setup.py
Add support for One-Cancels-Other (OCO) orders in the Tradier broker integration within the Lumibot trading library.
The changes are being made to enhance the functionality of the Lumibot library by allowing users to submit and manage OCO orders through the Tradier broker. This feature is crucial for traders who want to automate complex order strategies, such as setting simultaneous stop-loss and take-profit orders, where the execution of one cancels the other. The implementation includes parsing and submitting OCO orders, handling asset types, and updating order statuses to ensure robust order management.
=> Added tradier oco orders

lumibot/brokers/broker.py, lumibot/brokers/tradier.py, lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, lumibot/strategies/strategy_executor.py, lumibot/trading_builtins/custom_stream.py
Market Lifecycle methods such as before_market_opens(), before_market_closes(), and after_market_closes() were not being called correctly during live/paper trading due to how threading is used to handle the entire run_session.  These lifecycle methods were called properly for backtesting because it does not use threads for run_session.
Add lifecycle management improvements to the trading strategy execution, including new methods for handling market open and close times, and enhance logging and error handling in the broker and custom stream components.
These changes address the need for more precise control over trading strategy execution around market open and close times, ensuring lifecycle methods are called correctly in live trading sessions. Additionally, improved logging and error …
=> Lifecycle fixes

lumibot/brokers/broker.py
It appears that filled_quantity is not anymore positive, so the code should be updated.
This causes me a lot of errors printing in backtesting and even wrong backtest results.
This is my first PR on lumibot, please correct me if i'm wrong.
Remove the check that raises an error when `filled_quantity` is negative in `broker.py`.
The previous implementation incorrectly assumed that `filled_quantity` must always be positive, which is not necessarily true in all trading scenarios. This change allows for more flexibility in handling trade events where `filled_quantity` might be negative.
=> Fix error when filled_quantity is negative in broker.py

.gitignore, lumibot/backtesting/backtesting_broker.py, lumibot/data_sources/data_source_backtesting.py, lumibot/data_sources/yahoo_data.py, lumibot/example_strategies/stock_buy_and_hold.py, lumibot/strategies/_strategy.py, lumibot/tools/__init__.py, lumibot/tools/indicators.py, lumibot/traders/trader.py, tests/backtest/test_thetadata.py
1. many calls were being made to the root logger using ‘logging.info’ instead of ‘logger.info’
2. Noisy modules like trader and yahoo did not register themselves with the logger so they couldn’t be individually quieted.
3. There were some print statements sprinkled around too
4. Added option to not show the progress bar (useful when using not using quiet_logs for debugging strategies)
Replace `print` statements and `logging` calls with a unified `logger` instance across multiple modules, introduce a `quiet_logs` option to suppress noisy logs, and add a `show_progress_bar` option to control progress bar visibility during backtesting.
These changes improve the logging consistency and configurability of the codebase by using a dedicated logger instance, which allows for better log management …
=> Change some prints to logger; use logger instead of logging;

lumibot/data_sources/interactive_brokers_rest_data.py
Introduces infinite retries for some network requests.
Modify API request methods to disallow failures by default, adding retry logic for failed requests in `interactive_brokers_rest_data.py`.
These changes ensure that API requests are more robust by retrying upon failure, which reduces the likelihood of transient errors affecting the application's functionality. This approach improves reliability and user experience by handling temporary issues like rate limiting or network errors more gracefully.
=> Disallow failing in most API requests

lumibot/strategies/_strategy.py, lumibot/traders/trader.py, requirements.txt, setup.py
This feature enables the use of logger.info during backtests which will help developers when building strategies. It does so by removing the code that previously forced the logging level to ERROR when the backtest broker was in use.
To enable logging in backtests, the developer simply passes quiet_logs=False to Strategy.backtest() and then they can see all the logs from their strategy. The quiet_logs parameter defaults to true in Strategy.backtest() but is false in the Trader init function. This preserves the default behavior where there are lots of logs in live trading, but not many logs in local backtests.
This also fixes an issue with a recent deployment of yfinance
Modify the backtest logging settings to enable more info logs by default and update the `yfinance` library version in the …
=> Enable info logs in backtests

lumibot/backtesting/backtesting_broker.py, lumibot/data_sources/interactive_brokers_rest_data.py, lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, lumibot/strategies/strategy_executor.py
This pull request changes the log level of some unnecessary logs from info to debug. The logs affected are related to backtesting datetime, getting historical prices, sending account summary to Discord, and syncing the broker. This change will help reduce the noise in the logs and make it easier to focus on important information.
Change log level of specific log messages from `info` to `debug` across several modules within the codebase.
The affected log messages are deemed unnecessary for regular informational logging, potentially cluttering logs with less critical information. By switching these messages to `debug`, the logs will remain clearer and focused on more significant events unless debugging is specifically required. This adjustment aids in maintaining log clarity and efficiency. …
=> Change log level of unnecessary logs to debug

lumibot/backtesting/backtesting_broker.py, tests/backtest/fixtures.py, tests/backtest/test_pandas_backtest.py
The previous backtest broker didnt call update_datetime for daily runs (for some reason). Therefore it never changed the data of the backtest and it ran forever using the startdate. You can see this not working by running test_pandas_backtest.py using the original backtest broker before my changes. With my changes backtesting daily strategies with pandas now works.
Remove conditions that bypass awaiting market open and close logic for "PANDAS" data source with daily timestep.
The bypassing conditions prevented the daily backtests using Pandas from executing properly, leading to incomplete simulation scenarios. Removing these conditions ensures that the backtesting process accurately processes pending orders, resulting in more realistic and robust simulation outcomes.
> Is this description …
=> daily backtests with pandas didnt work. now they do

.gitignore, README.md, lumibot/backtesting/backtesting_broker.py, lumibot/credentials.py, lumibot/data_sources/yahoo_data.py, lumibot/example_strategies/lifecycle_logger.py, lumibot/strategies/_strategy.py, lumibot/tools/indicators.py, lumibot/traders/debug_log_trader.py, lumibot/traders/trader.py, tests/backtest/fixtures.py, tests/backtest/test_example_strategies.py, tests/backtest/test_pandas_backtest.py, tests/backtest/test_passing_trader_into_backtest.py, tests/backtest/test_polygon.py, tests/backtest/test_thetadata.py, tests/test_logging.py, tests/test_tradier.py
Found a bunch of places where I was setting the logger level to info unintentionally and removed those. Changed the traader to respect the quiet_logs property regardless of backtest or live trading. Updated the tests to skip ones that require an API key when no API key is present.
Implement enhancement for `quiet_logs` configuration to ensure it sets log levels correctly to reduce noise, add capability to skip tests that require API keys when those keys are unavailable, and update the README with backtesting instructions.
The previous log noise reduction feature wasn't functioning as intended due to non-conditional log level settings, which this change corrects by ensuring log levels are adjusted based on the `quiet_logs` parameter. Tests were failing unnecessarily when API keys weren't …
=> quiet_logs now works for realz. when no api keys, relevant tests are skipped.

README.md, lumibot/data_sources/alpaca_data.py, lumibot/data_sources/ccxt_backtesting_data.py, lumibot/data_sources/ccxt_data.py, lumibot/entities/bars.py, lumibot/entities/data.py, lumibot/example_strategies/stock_momentum.py, lumibot/tools/pandas.py, tests/backtest/test_pandas_backtest.py, tests/backtest/test_passing_trader_into_backtest.py, tests/backtest/test_polygon.py, tests/fixtures.py, tests/test_bars.py, tests/test_momentum.py, tests/test_pandas_data.py
Not all Bars had return columns. And only the yahoo Bars had returns that were dividend adjusted. Now all Bars have return a column. And when dividends are available, the returns will be dividend adjusted. 
Also, the get_momentum function now uses a lookback period instead of a start and end calendar date.This is more what people should expect (a 50 period lookback is 50 bars... not 50 calendar days).
Standardize the return calculation across all data sources in the Bars entity by adding a 'return' column, and modify the `get_momentum` method in Bars to utilize a lookback period instead of specific start and end dates.
The unified 'return' calculation simplifies handling various data sources, especially those with dividend adjustments, ensuring consistent return calculations across …
=> All Bars now all have return column; get_momentum now uses lookback instead of start/end

lumibot/backtesting/backtesting_broker.py, lumibot/entities/data.py, lumibot/entities/dataline.py, lumibot/strategies/strategy_executor.py, lumibot/tools/polygon_helper.py
Temporarily revert backtesting optimizations by restoring previous implementations in `backtesting_broker.py`, removing caching and data access enhancements, and reinstating older methods of data handling and time computations across several modules.
These changes revert recent optimizations to address possibly unanticipated issues or behavioral changes introduced by them, ensuring backward compatibility and stability in backtesting operations while further investigations or improvements can be planned.
=> Temp Revert backtesting optimizations

lumibot/data_sources/tradier_data.py, tests/test_bars.py
1. When asked for daily bars, tradier now returns bars with a Timestamp index just like all the other datasources (it was previously returning a date).
2. When asked to get daily bars and given a length of N and a timeshift of none, tradier now returns the last  N bars (instead of what it was doing before which was getting the bars for the last N days unlike the other datasources).
The following datasources now are tested for this stuff:
pandas, yahoo, alpaca, polygon, tradier.
(sorry i dont have any ibkr or thetadata accounts to test with)
Modify the `get_historical_prices` function to ensure it fetches the last `n` bars instead of bars from the past `n` days, and refactor test cases for clarity and correctness in `tradier_data.py`.
The change ensures accurate fetching of historical bars …
=> Get bars fixes

lumibot/backtesting/backtesting_broker.py, lumibot/brokers/alpaca.py, lumibot/brokers/broker.py, lumibot/tools/helpers.py, tests/backtest/test_brokers.py, tests/test_alpaca.py, tests/test_backtesting_broker.py, tests/test_helpers.py
This adds a new virtual method to the base broker. the _conform_order method is called during the broker.submit_order call and can be derived by brokers to adjust orders to broker requirements.
The Alpaca broker _conform_order method was implemented to adjust limit order prices.
Add an order conformance step to the `submit_order` process across brokers to ensure compliance with specific broker constraints before submission.
This change standardizes the order submission process by introducing an `_conform_order` method that ensures orders adhere to specific requirements, such as the price variance limit for limit orders in Alpaca. This improvement increases the reliability of the order processing pipeline across different brokers, preventing submission errors due to non-compliant orders. …
=> conform orders during submit_order

lumibot/entities/bars.py, lumibot/example_strategies/stock_momentum.py
Update the comment for the `get_momentum` method in `bars.py` to reflect the new signature with `num_periods=1` and correct the import path for `ALPACA_CONFIG` in `stock_momentum.py`.
The change to the `get_momentum` comment clarifies its updated function signature, ensuring documentation accuracy and reducing confusion for future developers. The import path correction for `ALPACA_CONFIG` addresses a module path error, likely caused by a restructuring in the project directory, ensuring the strategy functions correctly when executed.
=> update comments on get_momentum signature

lumibot/data_sources/pandas_data.py, lumibot/entities/data.py, lumibot/strategies/strategy.py, setup.py
Implement type-checking for the `length` parameter in the `get_historical_prices` function to ensure it is an integer, and update the package version in `setup.py` from 3.8.14 to 3.8.15.
The update addresses a bug where non-integer values for the `length` parameter in historical data retrieval could cause unexpected behavior, improving robustness by attempting to cast it to an integer and raising a meaningful error if casting fails. Incrementing the version number reflects this bug fix, improving package maintainability and version tracking.
=> bug fix for float in historical data

lumibot/brokers/interactive_brokers_rest.py, lumibot/data_sources/interactive_brokers_rest_data.py
Backported from the strategy overhaul PR as it is a pretty important fix
Refactor imports in `interactive_brokers_rest.py`, modify method names for clarity, enhance logging functionality, and improve error handling and retry logic in `interactive_brokers_rest_data.py`.
These changes resolve a hanging issue by refining import paths for consistency and encapsulating helper methods to prevent unwanted external invocation. Logging enhancements provide better traceability during retries, and improved error handling ensures reliability by retrying problematic requests under specific error conditions.
=> IB Fix for hanging issue

lumibot/brokers/broker.py, lumibot/brokers/interactive_brokers.py, lumibot/brokers/interactive_brokers_rest.py, lumibot/brokers/tradier.py, lumibot/credentials.py, lumibot/data_sources/alpaca_data.py, lumibot/data_sources/alpha_vantage_data.py, lumibot/data_sources/interactive_brokers_data.py, lumibot/data_sources/interactive_brokers_rest_data.py, lumibot/data_sources/pandas_data.py, lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py
The implementations of submit_order and submit_orders methods have been refactored with uniformity between brokers and ease of use as a priority.
1. In broker/tradier.py, broker/interactive_brokers_rest.py, etc. files, we have 2 functions: _submit_order and _submit_orders, handling single and multiple orders respectively.
2. In broker.py, these methods get wrapped by the submit_order and submit_orders methods. (No changes from before)
3. In strategy.py, these methods get combined into one submit_order method, which can handle both single and multiple orders. This was done as part of an effort to streamline the strategy class and make it more newcomer-friendly.
4. As per a user suggestion, when submitting multiple options orders at once, is_multileg is now automatically set to True
5. The …
=> Refactor strategy classes

lumibot/components/drift_rebalancer_logic.py, lumibot/example_strategies/drift_rebalancer.py
Refactor the logging mechanism to use the logger exclusively instead of directly logging messages to Discord.
These changes enhance modularity and maintainability by consolidating logging through a standard logger, reducing reliance on platform-specific logging (Discord). This refactor simplifies the code by removing redundant message formatting for broadcast and allows easier future adjustments to logging behavior or destinations without impacting individual logic flows.
=> Log to logger instead of discord.

lumibot/components/drift_rebalancer_logic.py, lumibot/example_strategies/drift_rebalancer.py
I had a lot of duplicate logging stuff, and i was sending discord messages. Ive been running this live for a few weeks and I don't need to babysit it as much. All the messages can be info logs now.
Refactor logging logic in the Drift Rebalancer component to streamline warnings and information messages, enhance data presentation with pretty printing, and remove redundant order status checks during backtesting.
These changes aim to improve the clarity and efficiency of the logging in the Drift Rebalancer component by restructuring warning conditions, reducing complexity in the rebalance execution flow, optimizing order logging, and removing unnecessary order status checks in backtesting scenarios to decrease noise. The enhanced data presentation helps in better understanding and debugging. …
=> Cleans up logging stuff.

lumibot/data_sources/tradier_data.py, lumibot/strategies/_strategy.py
Enhance error handling in `get_last_price` method of `tradier_data.py` by adding a try-except block and initialize cash-related variables in the strategy constructor of `_strategy.py`.
Errors in fetching asset prices can lead to unexpected crashes, so exception handling is added to improve robustness and logging in `tradier_data.py`. The initialization of cash-related variables in `_strategy.py` prevents potential attribute errors and ensures that they are setup when the strategy is initialized, which improves code reliability and clarity.
=> Fix for tradier

lumibot/example_strategies/crypto_important_functions.py, lumibot/example_strategies/forex_hold_to_expiry.py, lumibot/example_strategies/futures_hold_to_expiry.py, lumibot/example_strategies/lifecycle_logger.py, lumibot/example_strategies/options_hold_to_expiry.py, lumibot/example_strategies/simple_start_single_file.py, lumibot/example_strategies/stock_bracket.py, lumibot/example_strategies/stock_buy_and_hold.py, lumibot/example_strategies/stock_diversified_leverage.py, lumibot/example_strategies/stock_limit_and_trailing_stops.py, lumibot/example_strategies/stock_momentum.py, lumibot/example_strategies/stock_oco.py, lumibot/example_strategies/strangle.py, lumibot/example_strategies/test_broker_functions.py
Replace the use of Trader to run strategies with a direct call to strategy.run_live(), simplifying the execution process for live trading.
Refactor example strategy scripts to use `strategy.run_live()` instead of `Trader` instance management.
This change simplifies the execution process by replacing the use of a `Trader` object to manage and execute strategies with the direct invocation of `strategy.run_live()`. This refactor reduces redundancy and improves the clarity of strategy execution in live trading scenarios, making the example code easier to understand and maintain.
=> Implement strategy.run_live() in example strategies

lumibot/brokers/alpaca.py, lumibot/brokers/broker.py, lumibot/data_sources/interactive_brokers_rest_data.py, lumibot/entities/order.py
Add unprocessed orders to a tracking list upon order submission in the Alpaca broker integration.
Previously, orders that were submitted to Alpaca but not processed were not being tracked, potentially leading to discrepancies or missed updates. By appending such orders to the `_unprocessed_orders` list, we ensure more accurate tracking and handling of orders.
=> Fix for Alpaca order tracking

lumibot/backtesting/backtesting_broker.py, lumibot/data_sources/interactive_brokers_rest_data.py, lumibot/data_sources/tradier_data.py, lumibot/strategies/_strategy.py, lumibot/tools/thetadata_helper.py, tests/backtest/test_thetadata.py
When running a long backtest that goes across Daylight Savings transitions, lumibot is reporting the start time at 10:30am instead of 9:30am.  Basically the DST offset that existed when the backtest began continues through out the entire backtest regardless of DST transitions.  The fix is pretty straightforward which is to normalize the time after incrementing it with a timedelta() to ensure that the proper DST accounting takes place.
Additionally, all of the various timezone calls throughout the code have been standardized to use the Lumibot default.
Update timezone handling by using a unified timezone configuration `LUMIBOT_DEFAULT_PYTZ` for better consistency and fix daylight savings time issues in the `lumibot` codebase.
These changes address inconsistent timezone management which …
=> BackTest: Daylight Savings Fix

lumibot/brokers/ccxt.py
I was trying to submit buy/sell on DOGE and to then check the order completed. I ran into two issues.
1. timeInForce was None on existing open orders. These were created with Bitsgap and the parse code in ccxt.py assumes the key will exist, but it does not from Kraken for me on some orders.
2. when querying for closed orders the fetch to kraken API fails, I'm not fetching with margin, so I removed the dict as an arg to the api fetch and it works... I'm not sure where the API code for kraken is, possibly this part of the change could be done differently.
This change allows me to submit orders to kraken and check the status of orders.
Modify the CCXT broker in the Lumibot project to handle potential absence of the `timeInForce` key in the Kraken API response and ensure no parameters are …
=> Fix: Check timeInForce exists on Kraken API response.

lumibot/strategies/_strategy.py
Change logger level from warning to debug for message "No data found in the backup" in `_strategy.py`.
The absence of data in the backup is considered a normal situation and not indicative of a potential issue; hence logging it as a debug message is more appropriate than a warning. This reduces the noise of unnecessary warnings in the logs for expected scenarios.
=> change warning to debug

configurations/classic_60_40.py, lumibot/components/configs_helper.py, lumibot/example_strategies/classic_60_40.py, lumibot/strategies/strategy.py, tests/test_configs_helper.py
Introduce a `ConfigsHelper` class responsible for loading strategy parameters from configuration files and update the `classic_60_40` strategy to use this new class for parameter management.
These changes promote a more modular and maintainable code structure by separating configuration management from strategy logic, making it easier to reuse and manage configuration data. The added `ConfigsHelper` class provides a systematic approach to loading configuration parameters, facilitating future scalability and flexibility in handling configurations. Additionally, a test case is included to ensure the `ConfigsHelper` works as expected, reinforcing code reliability.
=> Added ConfigsHelper to components

tests/fixtures.py, tests/test_drift_rebalancer.py
Remove specific column selection from `pandas_data_fixture` and enhance `MockStrategyWithDriftCalculationLogic` by explicitly requiring a broker; add a new test to validate behavior when shorting more as prices increase.
These changes clean up unnecessary fixture details, ensuring the strategy instantiation explicitly acknowledges its dependency on a broker. The added test ensures robustness in handling scenarios where market conditions lead to increased shorting, thereby enhancing the Drift Rebalancer's accuracy in such situations.
=> Drift Rebalancer shorting tests

tests/backtest/test_polygon.py
Add a log message to `before_market_opens()` method in `test_polygon.py` to indicate when the market opens with the current datetime.
This change is introduced to provide better traceability and debugging information during testing by logging the moment of market opening, enhancing the visibility of the test execution flow.
=> small change to trigger github tests

tests/backtest/test_polygon.py
Replace `POLYGON_CONFIG` with `POLYGON_API_KEY` across all test cases in `test_polygon.py`, while removing checks related to `IS_PAID_SUBSCRIPTION`.
The change simplifies the test setup by directly using `POLYGON_API_KEY`, which is more straightforward for API authentication within test cases. Removing the `IS_PAID_SUBSCRIPTION` condition streamlines the tests because it focuses more on the necessity of having an API key rather than the subscription type, making tests more maintainable.
=> fixes to test_polygon

lumibot/backtesting/backtesting_broker.py, lumibot/brokers/broker.py, lumibot/tools/polygon_helper.py, tests/backtest/test_polygon.py
The main issue addressed in this branch is that multileg submissions were no longer returning the parent order that was created.  This was not caught by tests because BacktestingBroker uses an independent submission system from all of the rest of the brokers.  BacktestingBroker has now been updated to use the same methods as the live brokers so that future issues like this will be caught in regression testing.
- backtest_broker: Fixing backtesting_broker to use the same _submit_order() and _submit_orders() strategy as all the other brokers so that it can serve as a valid test for live. It missed a bug that prevented submitted orders from being returned correctly.
- broker: was no longer returning submitted orders, esp multileg parent orders.
- polygon_helper: get_chains caching was …
=> MultiLeg Parent Not Returned on Submission

lumibot/components/drift_rebalancer_logic.py, lumibot/example_strategies/crypto_50_50.py, lumibot/example_strategies/drift_rebalancer.py
Remove the method `DriftRebalancer.get_last_price` and consistently use `Strategy.get_last_price`, and update certain portfolio weights to reflect equal distribution in example strategies.
The `get_last_price` method in `DriftRebalancer` was redundant as its functionality can be achieved using `Strategy.get_last_price` with minor adjustments, leading to cleaner and more maintainable code. Additionally, adjusting the portfolio weights in example strategies reflects a balanced 50/50 asset distribution, which is easier to understand for users testing the strategies.
=> Remove DriftRebalancer.get_last_price and just use Strategy.get_last_price

lumibot/components/drift_rebalancer_logic.py, lumibot/example_strategies/classic_60_40_config.py, lumibot/example_strategies/crypto_50_50.py, lumibot/example_strategies/drift_rebalancer.py, tests/test_drift_rebalancer.py
Before the change, when a rebalance was triggered, all positions would reblance. That's still the default behavior, but now, you can set only_rebalance_drifted_assets, and only the assets that have drifted beyond the drift_threshold will rebalance. 
This is useful when rebalancing portfolios with lots of positions, some of which are volatile and some of which arent.
Add a `only_rebalance_drifted_assets` parameter to `DriftRebalancerLogic` and its associated classes and configurations, enabling selective rebalancing of assets that exceed a defined drift threshold.
This change provides users with a more efficient portfolio management option by rebalancing only those assets that have drifted beyond a specified threshold, thus optimizing trade executions and potentially reducing trading …
=> Added only_rebalance_drifted_assets parameter

lumibot/backtesting/polygon_backtesting.py, lumibot/backtesting/thetadata_backtesting.py, lumibot/brokers/broker.py, lumibot/data_sources/alpaca_data.py, lumibot/data_sources/ccxt_backtesting_data.py, lumibot/data_sources/ccxt_data.py, lumibot/data_sources/data_source.py, lumibot/data_sources/example_broker_data.py, lumibot/data_sources/interactive_brokers_data.py, lumibot/data_sources/interactive_brokers_rest_data.py, lumibot/data_sources/pandas_data.py, lumibot/data_sources/tradier_data.py, lumibot/data_sources/yahoo_data.py, lumibot/entities/bars.py, lumibot/entities/data.py, lumibot/example_strategies/ccxt_backtesting_example.py, lumibot/strategies/strategy.py, tests/backtest/test_example_strategies.py, tests/test_brokers_handle_crypto.py, tests/test_data_source.py, tests/test_drift_rebalancer.py, tests/test_get_historical_prices.py
Standardize the return type of `get_last_price` method across various data sources to `Union[float, Decimal, None]` and add unit tests for CCXT-based data handling.
Previously, the `get_last_price` method across the codebase was inconsistent in its return type, which could lead to errors or misinterpretations when handling asset prices. By standardizing to `Union[float, Decimal, None]`, the code enhances type consistency, allowing more precise handling of different numeric types and potential use of high-precision `Decimal` for financial computations. The addition of tests for the CCXT data source improves test coverage, ensuring that functionality related to this data source is correctly implemented and verified.
> Is this description stale? Ask me to generate a new description by …
=> Added tests for ccxt data. Standardized signature of get_last_price

lumibot/brokers/alpaca.py, lumibot/data_sources/alpaca_data.py, tests/test_alpaca.py, tests/test_get_historical_prices.py
This PR serves to add option in the Alpaca broker. This includes:
- Get last price taking an option contract
- Get historical prices taking an option contract
- Updating positions to know what a option contract is
Add support for retrieving last price and historical data for options via the Alpaca API.
The update enhances the Alpaca API integration by enabling access to option pricing data, meeting user demand for comprehensive option trading capabilities. This change addresses the gap in current functionality by supporting the retrieval of both real-time and historical data for options, ensuring better data handling and decision-making for users.
=> feat: Add option pricing to get last price and historical data on Alpaca

lumibot/entities/order.py, tests/test_order.py
This fixes `Position.avg_fill_price` being `None` when it's created from an `Order`.
Add `avg_fill_price` as a parameter when creating a position in the `to_position` method within the `order.py` file.
This change ensures that the average fill price is included in the position object, which is crucial for accurate backtesting and performance analysis. Without this addition, position objects may lack complete pricing information, impacting financial calculations and strategies.
=> fix(entities): pass avg_fill_price in to_position

lumibot/backtesting/alpaca_backtesting.py, lumibot/example_strategies/crypto_50_50.py, lumibot/example_strategies/crypto_50_50_config.py, lumibot/strategies/_strategy.py, tests/test_alpaca_backtesting.py, tests/test_drift_rebalancer.py, tests/test_get_historical_prices.py, tests/test_momentum.py
Add support for hourly data in Alpaca backtesting in the Lumibot library.
These changes enable more granular backtesting resolutions using Alpaca data, addressing the need for strategies that require hourly timeframes. Adjustments also streamline data-fetching parameters and make the system flexible with auto-adjustment types, enhancing utility and alignment with more precise trading strategy requirements.
=> Hourly data support in alpaca backtesting.

lumibot/backtesting/backtesting_broker.py, lumibot/brokers/alpaca.py, lumibot/brokers/broker.py, lumibot/brokers/ccxt.py, lumibot/brokers/interactive_brokers.py, lumibot/brokers/interactive_brokers_rest.py, lumibot/brokers/tradier.py, lumibot/components/drift_rebalancer_logic.py, lumibot/entities/asset.py, lumibot/entities/order.py, lumibot/example_strategies/stock_bracket.py, lumibot/example_strategies/stock_oco.py, lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, lumibot/tools/polygon_helper.py, lumibot/tools/yahoo_helper.py, setup.py, tests/backtest/test_example_strategies.py, tests/backtest/test_polygon.py, tests/fixtures.py, tests/test_drift_rebalancer.py, tests/test_order.py, tests/test_polygon_helper.py, tests/test_tradier.py
Advanced order handling of OCO/OTO/Bracket orders did not work in all contexts and brokers. There are also several confusing and deprecated features being utilized and all of these have been modified across all brokers so that the behavior is consistent going forward.
- `order.type` has been replaced with `order.order_type` to match (most) broker's terminology and to prevent shadowing with Python's built-in `type`.
- `order.order_type` no longer accepts "oco", "oto", or "bracket". These have been consolidated into the `order.order_class` parameter for clarity.
- `order.child_orders` is now populated automatically for all advanced order types at order creation time. Previously, each broker object was handling this themselves differently and it led to divergent and inconsistent behavior …
=> Order Management Overhaul

lumibot/example_strategies/classic_60_40.py, lumibot/example_strategies/crypto_50_50.py, lumibot/example_strategies/drift_rebalancer.py, lumibot/tools/helpers.py, tests/test_drift_rebalancer.py
Remove the `include_cash_positions` parameter from strategy setup to use a default configuration for cash handling except in `drift_rebalancer`, where it is explicitly set to `True`.
This change standardizes strategy configuration by removing the redundant `include_cash_positions` parameter, allowing the system's default handling of cash positions unless explicitly needed, like in the `drift_rebalancer` strategy. The updated approach minimizes code duplication and potential configuration errors across different strategy files.
=> Be alpaca backtesting

lumibot/credentials.py, lumibot/strategies/_strategy.py, lumibot/traders/trader.py
Add BACKTESTING_QUIET_LOGS and BACKTESTING_SHOW_PROGRESS_BAR environment variables to manage logging behavior during backtesting. These variables allow users to customize log visibility and progress bar display. Default values are set to ensure consistent behavior.
Introduce environment variables `BACKTESTING_QUIET_LOGS` and `BACKTESTING_SHOW_PROGRESS_BAR` to control the verbosity of backtesting logs and the display of progress bars in the Lumibot framework.
These changes provide users with greater customization over their backtesting environment by allowing them to suppress logs and control the display of progress bars through environment variables. This enhances the usability in varying development scenarios where users might require less console output or clean interfaces, and was …
=> Introduce environment variables for backtesting logging control

lumibot/strategies/strategy.py, lumibot/tools/indicators.py, tests/test_indicator_subplots.py
You can now add a plot_name when adding markers or lines. These will show up on their own subplot.
Add support for indicator subplots within the `lumibot` strategies, enabling markers and lines to be plotted on separate subplots; include test cases for default and named indicator strategies.
These changes enhance the visualization capabilities of the trading strategies by allowing for more organized and insightful displays of trading indicators. This improvement aids in better visual separation and categorization of markers and lines, potentially improving analysis and decision-making processes. The addition of test cases ensures the new functionality works as intended and maintains the existing system's integrity.
> Is this description stale? Ask me to generate a new description by …
=> Adding indicator subplots

lumibot/components/drift_rebalancer_logic.py, lumibot/data_sources/alpaca_data.py, lumibot/entities/order.py, lumibot/strategies/strategy_executor.py, tests/test_drift_rebalancer.py, tests/test_order.py
This branch was created to fix a warning that occurs when alpaca limit orders created with decimal prices somtimes dont "match" the float prices that get stored in the broker. It now converts decimals to floats and checks those making the warning go away.
However the more important changes are to the timestep mapping and _parse_source_timestep. I've reverted the changes made which broke everything.
Update the alpaca order handling logic to fix issues with limit price calculation, expand time-frame representations, improve order synchronization logic, and include additional tests for these functionalities.
These changes address specific issues with order limit prices by ensuring they correctly account for slippage and asset type, thereby improving precision in order execution. The …
=> Fix alpaca order issues (and more importantly fix the broken alpaca stuff)

lumibot/strategies/_strategy.py
Prioritize environment variables `BACKTESTING_START` and `BACKTESTING_END` over in-code declarations for backtesting dates and return an error if the `backtesting_end` date is in the future.
These changes ensure a consistent and predictable configuration by respecting environment variable settings over hardcoded defaults, which aids in dynamic configuration. The added validation prevents running a backtest with an end date set in the future, enhancing reliability and preventing potential errors in backtesting operations.
=> prioritize the backtesting_start and end env variables before in-code declarations. return error if backtest attempted with end date in the future

lumibot/data_sources/alpaca_data.py, tests/test_alpaca_data.py
Refactor `get_last_price` to utilize `get_quote` for fetching the last price and improve the accuracy of `last` field by correctly checking bid and ask values' presence in `get_quote`.
These changes address potential inaccuracies when calculating the last price from bid and ask values, and streamline the process by delegating price fetching tasks to `get_quote`. They also systematically handle cases where bid or ask prices might be zero, thus ensuring correct functionality. Additional tests have been added to verify changes and scenarios, improving robustness.
=> fix alpaca get_quote and get_last_price

.github/workflows/cicd.yaml, tests/test_alpaca_backtesting.py, tests/test_brokers_handle_crypto.py
Enable Alpaca and Tradier unit tests on GitHub by adding necessary test API keys and updating affected test assertions in `cicd.yaml` and `test_alpaca_backtesting.py`.
The changes allow for Alpaca unit tests to be correctly executed on GitHub, which requires providing API keys as environment variables. Additionally, test assertions have been updated to reflect the correct pricing of a stock that does not pay dividends or split, ensuring accuracy in the testing environment.
=> Enable alpaca unit tests on github

tests/test_brokers_handle_crypto.py
Fix the alpaca unit test by ensuring the date comparison uses New York timezone without the need for xfail.
The previous date comparison assumed the system's local time matched the New York timezone, leading to test failures in different environments; specifying the timezone explicitly resolves this discrepancy and enhances test reliability.
=> fix alpaca unit test without need for xfail

lumibot/brokers/alpaca.py
Hi team,
I just fixed a issue where alpaca cannot parse user provided custom parameters to the user.
Thanks
Scott
Enhance the Alpaca broker by allowing user-defined `custom_params` to be passed and integrated into order submissions.
This change facilitates greater flexibility and user customization within order processing by allowing strategy-level parameters to be directly incorporated into the order submission process. It addresses user needs for customized behavior beyond the default order parameters provided by the broker.
=> fixed alpaca broker to pass the custom params set by user to the broker.

lumibot/tools/polygon_helper.py
This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
Correct the logging interface method by replacing the deprecated `logging.warn` with `logging.warning` in the `polygon_helper.py` file.
The `logging.warn` method is deprecated and has been replaced by `logging.warning` to ensure compatibility with newer versions of Python and to adhere to best practices for logging methods. This change prevents potential warnings and errors in future Python releases.
=> Migrate to correct logger interface

tests/test_alpaca_data.py
Add `xfail` markers to two test cases in `test_alpaca_data.py` to account for timezone handling issues on GitHub.
The tests for fetching historical prices are currently failing due to timezone discrepancies when run on GitHub. Marking them as expected to fail (`xfail`) acknowledges the issue while allowing the test suite to proceed, acting as a temporary measure until a proper solution for handling timezones is implemented.
=> added xfail to handle weirdness.

lumibot/components/options_helper.py, lumibot/entities/order.py, lumibot/strategies/strategy_executor.py
This pull request contains a number of changes to make the library more Options friendly:
- Use multiplier for Options instead of hard-coded values
- Make get_increment() work properly for an Options order
Modify the calculation of order value for options by multiplying with a generic multiplier instead of the fixed value of 100 in the `_on_filled_order` method of `strategy_executor.py`.
This change generalizes the code to accommodate different option contract sizes other than the fixed multiplier of 100, enhancing the flexibility and accuracy of the order value calculation for various option types. This approach is necessary to support assets in markets where the multiplier might not be 100, providing a more adaptable solution.
> Is this description stale? Ask me to generate a new …
=> Make the library more Options friendly

lumibot/components/drift_rebalancer_logic.py
Update the quantization precision factor from `0.01` to `1.01` when calculating the limit price for both options and stocks in the drift rebalancer logic.
These changes are made to align with a quantization approach that has been consistently applied in the past, although this is not standard practice for securities trading which commonly uses cents for precision. This adjustment is presented as a method familiar to the author, though it might need re-evaluation to ensure it meets industry standards.
=> use 1.x for quantize because its what ive always done

lumibot/components/drift_rebalancer_logic.py
Implement a 'day' time_in_force parameter for orders in the drift_rebalancer logic to ensure orders do not carry over unexpectedly across trading days.
This change addresses potential issues that occur if orders remain uncompleted at the end of a trading day, especially in cases like asset splits that can lead to unexpected outcomes. Using 'day' time_in_force ensures orders are filled or canceled by the end of the trading day, reducing risk and improving system predictability.
=> use day time_in_force in drift_rebalancer

lumibot/backtesting/alpaca_backtesting.py, lumibot/backtesting/backtesting_broker.py, lumibot/brokers/alpaca.py, lumibot/brokers/bitunix.py, lumibot/brokers/broker.py, lumibot/brokers/ccxt.py, lumibot/brokers/interactive_brokers.py, lumibot/brokers/interactive_brokers_rest.py, lumibot/brokers/tradier.py, lumibot/data_sources/alpaca_data.py, lumibot/data_sources/data_source.py, lumibot/data_sources/tradier_data.py, lumibot/tools/pandas.py, tests/test_alpaca_data.py, tests/test_tradier_data.py
There are 3 distinct changes in this PR:
Previously, the broker.market member variable was inconsistently set across all brokers. Many didnt respect the MARKET environment variable and made assumptions about which market to set. The default values for all brokers has been preserved, however they all can now be overridden but the env var.
Additionally, all data source take a`delay` init parameter however its very hard to set that due to the way data sources are  automatically created everywhere (in credentials, in the brokers, in the strategy....). So I added a DATA_SOURCE_DELAY env var and changed the data_source default delay value. The result is that all default delay values persist (including alpaca's 16 minute delay) but if you wanted to override that (because you bought the paid …
=> Respect MARKET env var in all brokers; added DATA_SOURCE_DELAY env var

lumibot/entities/order.py, lumibot/tools/lumibot_logger.py, lumibot/traders/trader.py, tests/test_lumibot_logger.py
This pull request includes updates to improve logging functionality and enhance order handling logic. Key changes include refining logging formats and levels, introducing a new method to adjust console log verbosity, and clarifying behavior for updating child orders in specific scenarios.  This fixes several identified issues, however there are two big issues remaining:
1. Console printing gets reset after the first day of backtest completes 
2. Constant warnings are printed when running Live with sleeptime='10S'
* [`lumibot/tools/lumibot_logger.py`](diffhunk://#diff-c028dbd6ed61adf4917f70c7dfa258f7a0f31c116bb82e1ef39d73d4c9f21eb5R234-L250): Updated the `LumibotFormatter` to simplify the `info_format` by removing the `%(name)s` field, which was deemed unnecessary for most use cases. …
=> Logging and Multileg qty fix

lumibot/data_sources/projectx_data.py
Fixed time unit mappings for retrieve-bars api
https://gateway.docs.projectx.com/docs/api-reference/market-data/retrieve-bars
Update the `TIME_UNIT_MAPPING` dictionary in `ProjectXData` to include a mapping for "second" and adjust the indices accordingly for existing time units.
These changes correct the existing `TIME_UNIT_MAPPING` by adding support for "second" bars, aligning the indices to properly reflect the new mappings, ensuring accurate time unit representation for data processing. This modification facilitates the API's function to handle new data granularity and corrects previous inconsistencies in unit indexing.
=> ProjectX Time Unit Mappings API Fix

lumibot/data_sources/projectx_data.py, tests/test_projectx_timestep_alias.py
Add support for an alias parameter 'timestep' in the `get_bars` method and include associated unit tests to ensure functionality.
The change addresses a flexibility issue by allowing the `get_bars` method to accept a `timestep` parameter as an alias for `timespan`, accommodating a common parameter naming convention used by generic DataSource helpers. This improvement enhances code interoperability and streamlines the integration process with existing helper functions.
=> small bug fix

lumibot/brokers/projectx.py, lumibot/tools/projectx_helpers.py, tests/test_projectx_bracket_helpers.py, tests/test_projectx_bracket_lifecycle_unit.py
Implements synthetic bracket orders in ProjectX: parent entry spawns TP/SL children on fill; sibling auto-cancels on child fill (OCO).
Adds helpers for tag normalization, meta store/restore, price selection, and tick-size rounding.
Includes unit tests.
Add synthetic bracket order handling and associated tests in the ProjectX broker module to enable bracket order functionality.
These changes were necessary to implement synthetic bracket orders since ProjectX does not natively support bracket orders on the broker side. The implementation allows for creating, tracking, and processing bracket parent orders with synthetic take profit and stop loss child orders, ensuring they behave like real bracket orders including OCO (One Cancels Other) behavior. The tests ensure the new bracket handling …
=> ProjectX: Add synthetic bracket orders + tests

lumibot/data_sources/projectx_data.py
Last week's projectx changes flipped the retrieveBars call's "live" parameter from False to True. Can we change it back because the API call errors out and doesn't return any historical bars for me. The ProjectX just defines that param as "Whether to retrieve bars using the sim or live data subscription." I can't find any other info on it. If it's ok to set back to False here's the PR .
Set the live parameter to False in lumibot/data_sources/projectx_data.py when calling get_last_price.
To ensure the projectx data fetch uses non-live data for last price retrieval, avoiding live updates in this context. No other behavior changes beyond switching to non-live data sourcing.
=> Set live parameter to False in projectx_data.py
