lumibot/data_sources/yahoo.py, lumibot/strategies/_strategy.py, lumibot/tools/pandas.py
Used git grep "inplace", found three instances of `inplace=True`. Replace using `=`
=> Remove `inplace=True` in pandas as this will be deprecated.

lumibot/brokers/broker.py
Adding `wait_orders_clear` method around the sell_all to ensure all orders processed before and after the sell all.
=> Resolving sell_all bug.

lumibot/data_sources/interactive_brokers_data.py, lumibot/strategies/strategy.py
There was a design issue on my part where we were getting our single last price data from pull source bars. This was causing us to be unable to get one row of data for bars. 
Moved the `get_last_price` to its own method, and it now gets data from the `get_tick` method.
=> Moved get_last_price out of pull symbols bars. 

.mailmap
Added `.mailmap` file to account for my not using my proper email address.
=> Add mailmap to account for Neil using wrong email address.

lumibot/brokers/broker.py, lumibot/strategies/strategy_executor.py, lumibot/trading_builtins/safe_list.py
@grzesir There's still a couple of spots I need to look at when comparing the attributes of the orders. I'm not acting on that just yet, might not need to . 
Right now the bot is very resilient to change in the broker.  :)
**Use alpaca for today.**
Buy stocks, sell stocks, create and cancel orders.
=> Updating the recover pr to inclue syncing the bot while running.

lumibot/brokers/interactive_brokers.py, lumibot/data_sources/interactive_brokers_data.py, lumibot/entities/order.py, lumibot/strategies/strategy.py
I thought this was merged a while ago, my apologies.  @grzesir we likely need some documentation upgrade.  I need another quick lesson on the new doc process.
=> Time if force order created, gtc and gtd at IB Brokers.

lumibot/brokers/alpaca.py, lumibot/brokers/broker.py, lumibot/brokers/interactive_brokers.py, lumibot/data_sources/interactive_brokers_data.py, lumibot/strategies/_strategy.py, lumibot/strategies/examples/momentum.py, lumibot/strategies/strategy_executor.py, lumibot/traders/trader.py, tests/test_alpaca.py
Testing and fixing the combined previous pull requests. 
Changing how cash balances received from broker. 
Other minor changes.
=> This commit is tidying up of many previous pull requests 

lumibot/strategies/_strategy.py, lumibot/strategies/examples/fast_trading.py
Adding in better handling for positional and kwargs to migrate the strategy and budget to keyword arguments.
Minor change to update fasttrading.
Since it is now possible our users can have variable number of args, we can attempt to catch them and handle them instead of always throwing errors.
=> Improving on the migration of name and budget to positional arguments.

lumibot/backtesting/polygon_backtesting.py
test case: 
chains = self.get_chains(symbol)
chain = self.get_chain(chains, exchange="SMART")
expirations = chain["Expirations"]
expiration = list(expirations)[0]
print(f"lumibot_contract: {chains}")
print(f"Number of Contracts Found: {len(chain['Expirations'])}")
=> Update get_chains polygon_backtesting w/ test case

lumibot/backtesting/polygon_backtesting.py
Reverts Lumiwealth/lumibot#257
=> Revert "Update get_chains polygon_backtesting w/ test case"

.gitignore, .isort.cfg, lumibot/entities/asset.py, lumibot/entities/order.py, setup.cfg, tests/test_asset.py, tests/test_order.py
Removed unneeded "sec_type" parameter to prevent confusion. Also fixed failing Asset unit tests, cleaned up non-pythonic type checks, and added pytest caches to .gitignore.
=> Updating Order object to correctly return is_option() for calls.

.gitignore, lumibot/data_sources/alpaca_data.py
.venv is a commonly used naming convention for virtual environments which was not included before
=> Updated .gitignore And Alpaca To Work The Same As Other Brokers

lumibot/backtesting/backtesting_broker.py, requirements.txt, setup.py, tests/test_backtest_polygon.py, tests/test_backtesting_broker.py, tests/test_example_strategies.py
Applies to  for market, limit, and stop loss orders.
=> Backtesting updated to provide a more accurate fill prices

lumibot/entities/order.py, lumibot/tools/polygon_helper.py, requirements.txt, setup.py, tests/test_order.py, tests/test_polygon_helper.py
Refactored get_price_from_polygon() completely to be more efficient and eliminate multiple calls from looping. Polygon queries are not padded by 1 day for start/end to eliminate the possibility of intraday gaps in data.
=> 285 polygon issue with historical option data

.github/workflows/cicd.yaml, lumibot/backtesting/backtesting_broker.py, lumibot/brokers/broker.py, lumibot/brokers/interactive_brokers.py, lumibot/entities/order.py, lumibot/strategies/strategy_executor.py
Logging and small fixes for IBKR paper trading runs.
=> IBKR tweaks and cleanup

lumibot/backtesting/backtesting_broker.py, lumibot/brokers/interactive_brokers.py, lumibot/data_sources/alpaca_data.py, lumibot/data_sources/data_source.py, lumibot/entities/bars.py, lumibot/entities/order.py, lumibot/example_strategies/stock_bracket.py, lumibot/example_strategies/stock_oco.py, lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, lumibot/strategies/strategy_executor.py, lumibot/tools/helpers.py, lumibot/tools/indicators.py, lumibot/tools/yahoo_helper.py, setup.py, tests/backtest/test_example_strategies.py
Just fixing merge conflicts from Dev.  Once this is merged, the large branch can be committed into 'dev'
=> Ib broker dev resolve merge conflicts

lumibot/backtesting/backtesting_broker.py, lumibot/backtesting/polygon_backtesting.py, lumibot/example_strategies/stock_limit_and_trailing_stops.py, lumibot/strategies/_strategy.py, lumibot/strategies/strategy_executor.py, setup.py
it was settling at the beginning of day rather than the end
=> fixed bug with cash settling options

lumibot/backtesting/backtesting_broker.py, lumibot/data_sources/ccxt_data.py, lumibot/example_strategies/crypto_important_functions.py, lumibot/strategies/strategy.py, lumibot/tools/helpers.py
I'm currently working on a module for crypto bactest and have made some necessary changes. I'll re-commit when crypto backtest is complete.
=> modify for crypto

lumibot/brokers/tradier.py, tests/test_tradier.py
Simultaneously submitting buy and stoploss orders not working as both are trying to open positions with simultaneous "buy_to_open" and "sell_to_open".  This led to the stoploss executing 1st to open a short position and the normal Buy order was rejected with an exception:
```TradierApiError: Error: Backoffice rejected override of the order. | UnexpectedBuyOrder```
=> Tradier Stoploss orders are submitted with incorrect type

lumibot/backtesting/backtesting_broker.py, lumibot/brokers/alpaca.py, lumibot/brokers/broker.py, lumibot/brokers/ccxt.py, lumibot/brokers/interactive_brokers.py, lumibot/brokers/tradier.py, lumibot/data_sources/data_source.py, lumibot/data_sources/tradier_data.py, lumibot/entities/order.py, lumibot/strategies/strategy_executor.py, lumibot/trading_builtins/custom_stream.py, tests/backtest/test_polygon.py, tests/test_tradier.py
Lots of fixes to how Tradier Polling works to properly track orders and not double count in certain situations.
=> Open orders refactor

setup.py
@jimwhite @fovi-com @mrchaos @ishapiro deploying lumibot v3.2.2
=> v3.2.2 deployment

lumibot/backtesting/backtesting_broker.py
=> Add avg_fill_price to order in backtesting

lumibot/tools/polygon_helper.py
Fix polygon MaxRetryError for all calls  and keep POLYGON_IS_PAID_SUBSCRIPTION envar only if used
=> Fix polygon MaxRetryError for all calls 

lumibot/brokers/interactive_brokers.py
removed max_connection_retries as it is obsolete as per Robert's reconnect implementation 
makes lumibot update data source on reconnect. This ensures we can get price data after reconnection
> [!NOTE]
Remove the `max_connection_retries` parameter and the `connect_if_not_connected` method to simplify the IB reconnection logic.
The `max_connection_retries` parameter and the `connect_if_not_connected` method were redundant and added unnecessary complexity to the reconnection logic. By removing them, the code is cleaner and easier to maintain, while still ensuring reliable reconnection to the IB API.
=> Actually fix the IB Reconnection issues

lumibot/brokers/tradier.py, lumibot/traders/trader.py, setup.py
> [!NOTE]
Fix bugs in Tradier broker integration by sanitizing order tags and ensuring stock symbols are uppercase, and add validation for logfile path in trader initialization.
These changes address issues where Tradier rejects orders with invalid characters in tags and incorrect symbol casing, and ensure the logfile path is a valid string to prevent runtime errors. This approach improves the robustness and reliability of the trading system.
=> multileg bug fix for tradier

lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, setup.py
> [!NOTE]
Fix the bug related to sending account summaries to Discord by adding a new configuration option `should_send_summary_to_discord` and updating the `Vars` class initialization.
The previous implementation did not allow for conditional sending of account summaries to Discord, causing issues when the Discord webhook URL was set but summaries were not desired. This change introduces a new flag to control this behavior, ensuring more flexible and error-free operation. Additionally, the `Vars` class initialization is updated to use `super().__setattr__` for better attribute management.
=> Discord account summary bug fix

lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, lumibot/strategies/strategy_executor.py
> [!NOTE]
Refactor database backup functionality to use a dedicated backup table and improve the backup and restore logic.
The previous implementation used the strategy name as the table name, which could lead to conflicts and was not scalable. The new approach uses a dedicated table (`vars_backup`) and includes logic to create the table if it does not exist, ensuring a more robust and maintainable backup process.
=> Restructure of db backup tables

.gitignore, lumibot/strategies/_strategy.py, lumibot/strategies/credentials.py, lumibot/strategies/strategy.py
> [!NOTE]
Integrate `credentials.py` to replace hardcoded configuration values in `_strategy.py`.
This change centralizes configuration management, making the codebase more maintainable and secure by avoiding hardcoded sensitive information. Additionally, it simplifies the process of updating credentials and other configuration values.
=> Integrated credentials.py

lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, lumibot/strategies/strategy_executor.py, setup.py, tests/backtest/test_polygon.py, tests/test_order.py
> [!NOTE]
Update the version number in `setup.py` from 3.6.4 to 3.6.5.
This change reflects the release of version 3.6.5, which includes the latest updates and bug fixes. Updating the version number ensures that users can identify and install the correct version of the package.
=> v3.6.5 released

lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, setup.py
> [!NOTE]
Fix the `get_stats_from_database` method to use a parameterized query, ensure `quote_assets` attribute exists on the broker, and update the package version to 3.6.9.
The `get_stats_from_database` method was vulnerable to SQL injection due to the use of a raw query string; switching to a parameterized query enhances security. The addition of the `quote_assets` attribute check ensures robustness when interacting with the broker. The version update reflects these changes and improvements.
=> bug fix for get_stats_from_database

lumibot/brokers/ccxt.py, lumibot/brokers/interactive_brokers.py, lumibot/data_sources/interactive_brokers_data.py, setup.py
> [!NOTE]
Fix a bug in the Interactive Brokers integration to correctly retrieve the last price by initializing additional tick attributes and updating the data extraction logic.
The previous implementation did not properly initialize certain tick attributes, leading to incorrect or missing last price data. This fix ensures that all necessary attributes are initialized and the correct price is extracted, improving data accuracy and reliability.
=> IB get last price bug fix

lumibot/strategies/strategy.py, setup.py
> [!NOTE]
Fix the bug in the `discord summary` by ensuring that DataFrames are correctly indexed before saving to the database.
The previous implementation did not set the index for DataFrames before saving them to the database, which caused issues with data integrity and retrieval. This fix ensures that the &#x27;id&#x27; column is set as the index, maintaining consistency and preventing potential errors. Additionally, the version number in `setup.py` has been incremented to reflect this bug fix.
=> discord summary bug fix

lumibot/entities/order.py, lumibot/strategies/credentials.py, lumibot/strategies/strategy.py, lumibot/strategies/strategy_executor.py, setup.py, tests/test_order.py
Add `is_buy_order` and `is_sell_order` methods to the `Order` class, enhance logging with colored messages for `.env` file loading, fix typos in docstrings, update the order handling logic in `strategy_executor.py`, and increment the package version.
The new methods improve order type checks, colored logging enhances readability, typo fixes improve documentation clarity, and the updated order handling logic ensures correct emoji display. The version increment reflects these updates.
=> fixed a few bugs

lumibot/backtesting/backtesting_broker.py, setup.py
Refactor order side checks in `submit_order` method to use `is_buy_order` and `is_sell_order` methods, and update the package version to 3.6.17.
The previous implementation had hardcoded strings for order sides, which could lead to errors and was less maintainable. The new approach uses dedicated methods to improve code readability and reliability. The version bump reflects this bug fix.
=> fixed sell short bug for backtesting

lumibot/credentials.py, lumibot/strategies/_strategy.py, lumibot/tools/polygon_helper.py, setup.py
Refactor `lumibot/credentials.py` to remove the `credentials` dictionary and replace it with individual variables, and update all references accordingly.
This change simplifies the code by removing the unnecessary `credentials` dictionary, making the code more readable and maintainable. It also aligns with best practices for handling environment variables and configuration settings.
=> some fixes to the credentials file

docs/_sources/backtesting.thetadata.rst.txt, lumibot/backtesting/thetadata_backtesting.py, lumibot/credentials.py, lumibot/data_sources/pandas_data.py, lumibot/entities/data.py, lumibot/tools/thetadata_helper.py, tests/backtest/test_thetadata.py, tests/test_thetadata_helper.py
1. Enabled bid/ask feature with thetadata 
2. Added 36 unit testing feature for thetadata_helper.py
3. Won't show thetadata download on weekends
> [!NOTE]
Added support for fetching and handling bid/ask quote data from ThetaData, including new methods, updated caching mechanisms, and comprehensive unit tests.
These changes enhance the backtesting capabilities by incorporating bid/ask quote data, which is crucial for more accurate and realistic simulations. This update also includes improvements in data handling, caching, and error management to ensure robustness and reliability.
=> Theta bidask

docsrc/entities.order.rst, lumibot/brokers/broker.py, lumibot/entities/order.py, setup.py
Fix the `get_increment` method to return a float value and update related documentation and code to handle this change.
The `get_increment` method previously returned an integer, which caused issues when performing calculations with floating-point precision. This change ensures that the method returns a float, improving accuracy in order quantity calculations. Additionally, the documentation and related code have been updated to reflect this change.
=> increment bug fix

lumibot/brokers/broker.py, lumibot/brokers/tradier.py, lumibot/strategies/strategy.py, setup.py
Fix minor issues in Tradier API error handling, improve logging for Discord messages, and correct a typo in the `send_result_text_to_discord` method.
These changes enhance error handling for Tradier API interactions by providing more informative error messages and logging, improve the clarity of Discord messages, and fix a typo to ensure accurate information is communicated.
=> minor fixes for tradier and discord messages

docsrc/backtesting.polygon.rst, docsrc/backtesting.thetadata.rst
Replaced manual run backtesting strategy steps with MyStrategy.run_backtest()
Refactor the backtesting documentation for Polygon and ThetaData to use the `MyStrategy.run_backtest` method.
This change simplifies the backtesting setup by consolidating the initialization and execution steps into a single method call, improving code readability and maintainability.
=> New layout on polygon and thetadata

lumibot/strategies/_strategy.py, setup.py
Fix the logic for setting ThetaData credentials and update the data source initialization to handle different backtesting classes, along with a version bump in `setup.py`.
The previous logic incorrectly checked for ThetaData credentials, potentially causing errors when using `ThetaDataBacktesting`. The updated logic ensures credentials are set correctly and initializes the data source appropriately based on the class type, improving reliability and functionality. The version bump reflects these changes.
=> theta data bug fix

lumibot/backtesting/thetadata_backtesting.py, lumibot/tools/thetadata_helper.py, setup.py
Add error handling for &quot;NO_DATA&quot; responses in ThetaData backtesting and update the package version to 3.7.0.
These changes address the issue of handling cases where no data is returned from ThetaData, preventing potential errors in data processing. The version update reflects the addition of this new error handling feature.
=> added error handling for NO_DATA in theta data

lumibot/strategies/_strategy.py, setup.py
```markdown
Fix the logic for retrieving option prices when updating portfolio values and increment the package version to 3.7.1.
The previous implementation incorrectly handled the retrieval of option prices, potentially leading to inaccurate portfolio valuations. The updated logic ensures that option prices are fetched from the correct source, improving the accuracy of portfolio updates. The version bump reflects this bug fix.
```
=> bug fix for option_source when updating portfolio values

lumibot/credentials.py, lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, lumibot/strategies/strategy_executor.py, setup.py
Add settings to hide trades and positions, including environment variable checks and logging, and update the strategy execution logic to respect these settings.
These changes provide users with the option to hide trade and position details, enhancing privacy and control over what information is shared, particularly in environments where sensitive data might be exposed. The implementation includes environment variable checks with default fallbacks and logging for invalid inputs, ensuring robustness and user awareness.
=> add hide trades and positions settings

lumibot/strategies/_strategy.py, setup.py
> [!NOTE]
> I'm currently writing a description for your pull request. I should be done shortly (<1 minute). Please don't edit the description field until I'm finished, or we may overwrite each other.
=> td bug fix

lumibot/strategies/strategy_executor.py, lumibot/tools/polygon_helper.py, tests/backtest/test_example_strategies.py, tests/test_polygon_helper.py
Small update to correctly pass along Index symbols like SPX.
Add support for handling index assets in the `get_polygon_symbol` function and enhance lifecycle methods with `@trace_stats` decorator in `strategy_executor.py`.
The changes are made to enable the system to correctly identify and process index assets by prefixing them with "I:" in the symbol, which is necessary for accurate data retrieval from Polygon. The `@trace_stats` decorator is added to lifecycle methods to facilitate better performance monitoring and debugging. Additionally, test cases are updated to reflect these changes and ensure robustness.
=> Polygon indicies support

lumibot/credentials.py, setup.py
=> added LIVE_CONFIG to creds

docsrc/deployment.rst, docsrc/index.rst, lumibot/brokers/tradier.py, lumibot/entities/asset.py, lumibot/entities/order.py, lumibot/entities/position.py, lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, lumibot/traders/trader.py, setup.py
Add a comprehensive deployment guide for Render and Replit, implement serialization methods for entities, fix bugs related to order quantity and Discord webhook checks, and update the package version to 3.7.7.
The deployment guide is added to assist users in deploying applications easily on Render and Replit, which are popular platforms. Serialization methods are introduced to facilitate the conversion of entities to and from dictionaries, enhancing data handling capabilities. Bug fixes address issues with order quantity type casting and ensure proper checks for Discord webhook URLs, improving the robustness of the application. The version update reflects these enhancements and fixes.
> Is this description stale? Ask me to generate a new description by commenting …
=> improved docs, serialization for entities and bug fixes

lumibot/brokers/tradier.py, lumibot/entities/order.py, lumibot/strategies/strategy_executor.py
Refactor order serialization and deserialization methods to handle non-serializable attributes, improve error handling in order retrieval, and enhance logging in strategy initialization and execution.
The changes address a bug in order serialization by excluding non-serializable attributes and converting datetime objects to a serializable format, ensuring robust error handling when retrieving orders from Tradier, and improving logging clarity during strategy lifecycle events. This approach enhances code reliability and maintainability, while providing better insights during strategy execution.
=> bug fixes for order serialization

setup.py
Update the `lumiwealth-tradier` package version requirement from `>=0.1.10` to `>=0.1.12` in `setup.py`.
The update ensures compatibility with the latest features and bug fixes provided in the newer version of the `lumiwealth-tradier` package. This change is necessary to maintain the stability and functionality of the software that depends on this package.
=> update tradier version

lumibot/credentials.py, lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, lumibot/strategies/strategy_executor.py
Add a method `send_update_to_cloud` to the `Strategy` class to send portfolio updates to the LumiWealth cloud server, and integrate this method into the trading iteration process.
These changes enable the strategy to send real-time updates of portfolio value, cash, positions, and orders to the LumiWealth cloud server, allowing users to track their bot's performance online. The integration of the API key ensures secure communication, and the method is only invoked during live trading, not backtesting, to prevent unnecessary data transmission.
=> added send_update_to_cloud

lumibot/backtesting/thetadata_backtesting.py, lumibot/strategies/_strategy.py, lumibot/tools/thetadata_helper.py
Also added more exception handling so long runs don't crash when an exception is thrown.
Add a flag to disable the use of quote data by default in the `thetadata_backtesting.py` module and refactor the data update logic to conditionally include quote data based on this flag.
These changes provide flexibility in backtesting by allowing users to opt-out of using quote data, which can be unnecessary for certain analyses and can improve performance by reducing data processing overhead. The refactoring also simplifies the code by removing redundant data update logic and handling exceptions more gracefully.
=> Added a flag that turns off using quote data by default

lumibot/data_sources/interactive_brokers_rest_data.py
Refactor the logic for determining if the application is running on a server and remove redundant Docker process checks in the Interactive Brokers REST data source.
The changes simplify the code by consolidating the server check logic and removing unnecessary Docker process verifications, which are redundant when the application is confirmed to be running on a server. This improves code readability and efficiency by eliminating superfluous operations.
=> Hopefully Last small IB Render Fixes

lumibot/brokers/interactive_brokers_rest.py, lumibot/data_sources/interactive_brokers_rest_data.py
Fix the handling of forex positions and the retrieval of the last price in the Interactive Brokers REST integration by initializing cash to zero, adding a warning for zero-quantity forex assets, and adjusting the return type for historical price retrieval.
These changes address issues with forex position calculations and ensure that the system provides a warning when a selected quote asset has zero quantity, which could lead to incorrect trading decisions. Additionally, the return type for historical prices is adjusted to prevent errors when no data is retrieved, improving the robustness of the data handling.
=> fixed forex positions and get-last-price for ib rest

lumibot/backtesting/backtesting_broker.py, lumibot/credentials.py, lumibot/entities/position.py, lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py
Add a bot listener to the Lumibot by updating the backtesting broker, credentials, position entity, and strategy classes to improve functionality and error handling.
These changes are made to enhance the robustness and flexibility of the Lumibot system by ensuring that empty orders are handled gracefully, environment variables are utilized for configuration, and error handling is improved when sending updates to the cloud. Additionally, the changes streamline the backtesting process by removing deprecated positional arguments and ensuring default values are set from environment variables.
=> added bot listener to lumibot

lumibot/brokers/interactive_brokers_rest.py, lumibot/credentials.py, lumibot/data_sources/interactive_brokers_rest_data.py, lumibot/strategies/_strategy.py
Replace `ValueError` exceptions with logging for error handling and implement authentication checks and retries for Interactive Brokers API interactions.
The changes improve the robustness of the system by logging errors instead of raising exceptions, which can halt execution. This is particularly useful for handling unexpected asset types and empty order lists. Additionally, the introduction of authentication checks and retries ensures that the system can recover from temporary authentication issues with the Interactive Brokers API, enhancing reliability and user experience.
=> Handle authentication issues with IB

lumibot/strategies/strategy.py
Remove the retrieval of the current time in New York and the associated `datetime` field from the data sent to the cloud, and update the URL for sending portfolio events to the Lumiwealth listener.
The current time in New York is no longer necessary for the data being sent, simplifying the data structure and reducing potential errors related to time zone handling. The URL update reflects a change in the endpoint for sending portfolio events, ensuring that data is sent to the correct location.
=> bot listener working now!

lumibot/strategies/_strategy.py, lumibot/tools/polygon_helper.py
Fix the initialization of the logger in the strategy class and correct the conditional expression for date range checks in the polygon helper.
Previously, the logger was incorrectly reinitialized, which has now been fixed by checking its existence before initializing. For the polygon helper, the added parentheses enhance readability, ensuring correct calculations of date range for data queries, aligning with best practices for clear and maintainable code.
=> bug fixes for logger and polygon

lumibot/backtesting/backtesting_broker.py, lumibot/brokers/interactive_brokers_rest.py, lumibot/data_sources/interactive_brokers_rest_data.py, lumibot/entities/__init__.py, lumibot/entities/data.py, lumibot/entities/dataline.py, lumibot/strategies/strategy_executor.py, lumibot/tools/polygon_helper.py
Optimize backtesting performance by caching index searches, implement SPX-related fixes for Interactive Brokers by accurately rounding prices via contract rule increments, and refactor data handling for time series and market schedule caching to improve efficiency.
These changes address the critical issue of inefficiency in backtesting due to repetitive index searching and the need for accurate price calculations pertaining to the SPX index in Interactive Brokers. The caching strategy for indices and market schedules significantly reduces computation time and API calls, thus enhancing performance. Additionally, refactoring data handling makes the system more consistent and reliable while rounding prices according to contract rules ensures appropriate market operations.
> Is this …
=> Backtesting Optimizations + SPX Fix for IB

lumibot/brokers/broker.py, lumibot/brokers/interactive_brokers_rest.py, lumibot/data_sources/interactive_brokers_rest_data.py, lumibot/strategies/strategy.py
Enhance the handling of position objects by ensuring accurate representation and filtering out positions with zero quantity. This update also improves the logic for processing futures and orders.
Fix the representation of position objects by modifying the filtering logic for zero quantity positions and improve asset detail retrieval, specifically by updating condition checks, refining symbol handling, and correcting asset information retrieval.
These changes are being made to ensure accurate handling and representation of position objects within the broker system, particularly to prevent adding positions with zero quantities, improve symbol parsing for option contracts, and correct attribute assignments for futures, thereby enhancing data integrity and consistency. This approach resolves …
=> Fix position object representations and improve filtering for zero quantity positions

lumibot/example_strategies/drift_rebalancer.py
Log the status of submitted orders to a Discord channel in addition to logger info in the `drift_rebalancer.py` strategy.
These changes are implemented to enhance the visibility and traceability of order statuses by broadcasting them to a Discord channel. This aids in keeping stakeholders informed in real-time and facilitates better monitoring and debugging of the rebalance process.
=> log status of submitted orders to discord

lumibot/data_sources/interactive_brokers_rest_data.py
Implement more rigorous retry policies to improve the reliability of requests to the IB API.
Enhance retry policies for HTTP requests within the Interactive Brokers REST data source by restructuring error handling in `get_from_endpoint`, `post_to_endpoint`, and `delete_to_endpoint` methods, and introducing more detailed logging and error message consistency.
These changes improve the robustness of the API request handling by introducing systematic retries for transient errors (such as server errors and rate-limiting), providing more informative log messages on retries, and ensuring consistency in error responses. This enhancement aims to reduce system downtime caused by temporary failures and improve debugging capabilities through clearer logs.
> Is this description stale? Ask me to …
=> Enhance retry policies for IB API requests

lumibot/example_strategies/drift_rebalancer.py
Add enhanced logging with a broadcast feature when rebalancing in the drift_rebalancer.py script.
To provide better visibility into the rebalancing process by not only logging the order status but also broadcasting this information, which is useful for monitoring and debugging purposes. This ensures that order statuses are communicated more effectively across different components or team members that might be monitoring the rebalancing activity.
=> add logging when rebalancing

lumibot/brokers/interactive_brokers_rest.py, lumibot/data_sources/interactive_brokers_rest_data.py, lumibot/entities/asset.py, lumibot/entities/order.py
Implement trade event handling and error management improvements for Interactive Brokers (IB) integration.
These changes enhance the reliability and functionality of the Interactive Brokers integration by introducing comprehensive error handling, updating order status mapping, and supporting trade event-driven architecture through `PollingStream`. The improvements ensure accurate synchronization with the broker's data and provide better logging and notification mechanisms for order lifecycle events.
=> Error handling yet again and trade events working for IB

lumibot/brokers/interactive_brokers_rest.py, lumibot/data_sources/interactive_brokers_rest_data.py, lumibot/entities/asset.py, lumibot/entities/order.py, setup.py
Integrate new polling stream support and enhanced order handling into the Interactive Brokers REST broker implementation, and update the asset types and order statuses.
We are shifting from a websocket-based connection to a polling mechanism for better reliability of receiving market data and order status updates from the Interactive Brokers API. These changes improve error handling and make the system more robust against connection disruptions. Additionally, by extending support for 'multileg' assets and refining status mappings, we ensure broader compatibility with broker responses and improve overall trading strategy execution. The package version is incremented to reflect these significant updates, and `websocket-client` is added as a new dependency.
> Is this description stale? Ask …
=> merge dev into be-dev

lumibot/brokers/interactive_brokers_rest.py, lumibot/data_sources/interactive_brokers_rest_data.py, lumibot/example_strategies/forex_hold_to_expiry.py, lumibot/example_strategies/futures_hold_to_expiry.py
Refactor future and forex contract handling in `interactive_brokers_rest.py` and `interactive_brokers_rest_data.py`, add example strategy scripts for holding futures and forex until expiry.
The refactoring of contract handling functions improves the accuracy and flexibility of derivative asset management by specifying exchange parameters and adjusting retry limits. Additionally, the example strategy scripts are provided to demonstrate practical uses of the system for trading futures and forex assets, enhancing the educational value of the codebase for users interested in programmatically implementing similar strategies.
=> Futures fix, example futures and forex strategies

lumibot/data_sources/interactive_brokers_rest_data.py, lumibot/strategies/strategy_executor.py
Remove the condition that checks if the code is not in a trading iteration before sending updates to the cloud in the `_run_trading_session` function of `strategy_executor.py`.
The removed condition caused delays in cloud updates when a trading iteration was ongoing, leading to potential synchronization issues with cloud data. By removing the restriction, data synchronization with the cloud can occur promptly every minute, enhancing data consistency and reducing the likelihood of incomplete data syncs.
=> potential fix for the send update to cloud function

lumibot/components/drift_rebalancer_logic.py
If you have smaller positions, sometimes they won't get filled because you have run out of cash. Sort the sells and buys so the biggest changes in drift get processed first.
Update the rebalancer logic to sort sell and buy orders based on the largest absolute drift and consolidate logging into batch messages for both orders and drift summaries.
Sorting by the biggest drift ensures that the most significant discrepancies are addressed first, optimizing the rebalancing process. Consolidated messaging enhances readability and reduces redundancy in logs, making the rebalancer more efficient and easier to debug.
=> When rebalancing, sort the sells and buys by biggest drift first.

lumibot/data_sources/interactive_brokers_rest_data.py
Reduce frequent error logging in `handle_http_errors` by introducing a parameter `allow_fail` and conditionally limiting logs with a helper function `show_error`, while modifying method invocations to support the new parameter.
The current logging mechanism outputs too frequently, causing unnecessary clutter in logs and making it difficult to identify crucial error messages. By using the `allow_fail` parameter and the `show_error` function, we strategically limit log outputs based on retry intervals and conditions, improving log readability and system performance.
=> Reduce error logging for IB operations

lumibot/entities/order.py
Add "cash_settled" as a valid fill type in the `is_filled` method of the `order` entity class.
This change accounts for scenarios where orders are settled in cash, necessitating the inclusion of "cash_settled" in the list of status indicators that determine if an order is considered filled. This enhancement ensures accurate tracking and accounting for all types of order settlements.
=> order: adding "cash_settled" as a valid fill type.

lumibot/data_sources/interactive_brokers_rest_data.py
Refactor error handling in Docker interactions and HTTP requests for better clarity and reliability, and explicitly remove and restart Docker containers before initiating connections.
These changes ensure clearer error messaging around Docker services and improve response handling for situations where Interactive Brokers might be unavailable due to weekend maintenance. This approach enhances the robustness and reliability of the service connection, while also handling exceptions more gracefully.
=> fixes for docker messages + fixes for ib weekend maintenance errors

lumibot/components/drift_rebalancer_logic.py, lumibot/data_sources/yahoo_data.py, lumibot/entities/data.py, tests/test_drift_rebalancer.py, tests/test_get_historical_prices.py
Refactor drift rebalancer logic to include short position covering, extend tests for shorting scenarios, and add strategy and broker names to cloud updates.
The refactor improves the rebalancer logic to handle short positions correctly when shorting is enabled, ensuring accurate trading actions. Tests have been expanded to verify the robustness of these changes. The addition of strategy and broker details to cloud updates enhances tracking and monitoring capabilities.
=> Fix polygon get historical prices

lumibot/strategies/_strategy.py, setup.py
Refactor configuration file path and update function parameter typing in strategy logic.
The configuration path was updated to improve organization under `example_strategies`, ensuring consistency in naming conventions across files. Additionally, specifying the `datetime` type for `backtesting_start` and `backtesting_end` improves code clarity and type safety, aligning with best practices in Python code design and reducing potential runtime errors caused by improper argument types.
=> config helper changes 

lumibot/backtesting/polygon_backtesting.py, lumibot/entities/asset.py, lumibot/entities/order.py, lumibot/entities/position.py, lumibot/strategies/strategy.py, lumibot/tools/polygon_helper.py, setup.py, tests/test_polygon_helper.py
Integrate caching for the `get_chains` method in the Polygon backtesting module to improve performance by reducing redundant API calls.
The caching functionality aims to speed up the backtesting process by avoiding repeated downloads of unchanged option chain data. By reusing recent chain files, we reduce API call overhead, especially when backtests query similar date ranges multiple times. This approach balances between data accuracy and performance efficiency by using a seven-day tolerance for caching while still allowing fresh data retrieval when necessary.
=> added caching to get chains to improve speed

lumibot/components/drift_rebalancer_logic.py, lumibot/example_strategies/classic_60_40_config.py, lumibot/example_strategies/crypto_50_50.py, lumibot/example_strategies/drift_rebalancer.py, tests/test_drift_rebalancer.py
=> Added only_rebalance_drifted_assets parameter

lumibot/data_sources/pandas_data.py, lumibot/entities/data.py, lumibot/strategies/_strategy.py, lumibot/tools/polygon_helper.py, setup.py, tests/test_get_historical_prices.py
Modify the `polygon_helper.py` to more accurately determine missing dates by only treating dates entirely not present in the DataFrame as missing, update the methodology for merging data from Polygon to ensure non-duplicate, complete data, and adjust the `backtesting_end` variable in `_strategy.py` to set the end date to the current date minus one day by default.
The existing logic for identifying missing data in the `polygon_helper.py` was too aggressive, often redownloaded data unnecessarily for dates that contained non-essential NaN values. Handling of the end date in `_strategy.py` was adjusted to provide a more accurate, deterministic default value, improving user experience and reducing potential confusion when backtesting around current dates. Additionally, updating the package …
=> fixed a bug with missing dates in polygon helper

lumibot/brokers/__init__.py, lumibot/brokers/tradeovate.py, lumibot/credentials.py, lumibot/data_sources/__init__.py, lumibot/data_sources/tradeovate_data.py
Integrate Tradeovate as a new broker and data source within the `lumibot` library by adding a `Tradeovate` broker class, corresponding data source class `TradeovateData`, updating credentials and initialization scripts, and including API interaction methods.
These changes introduce support for the Tradeovate platform within the `lumibot` framework, enabling users to connect, retrieve market data, manage accounts, and place orders via Tradeovate. This enhances `lumibot`'s capabilities by broadening the available broker options and was chosen as it allows seamless integration with Tradeovate's API. However, some Tradeovate-specific methods are currently logged as 'not yet implemented' placeholders and will need to be completed for full functionality.
> Is this description stale? Ask me to …
=> Tradeovate

lumibot/strategies/_strategy.py, lumibot/strategies/strategy.py, tests/backtest/test_pandas_backtest.py, tests/test_alpaca_backtesting.py, tests/test_drift_rebalancer.py, tests/test_momentum.py
=> stop analyzing backtests in unit tests

lumibot/strategies/strategy.py
=> add type hint for tuple to support crypto

lumibot/backtesting/alpaca_backtesting.py, lumibot/data_sources/tradier_data.py, lumibot/entities/data.py, tests/backtest/test_main_pandas_daily.py, tests/test_alpaca_backtesting.py
=> Remove trading hours

lumibot/brokers/__init__.py, lumibot/brokers/broker.py, lumibot/brokers/tradier.py, lumibot/strategies/strategy.py, lumibot/strategies/strategy_executor.py, tests/test_tradier.py
This pull request introduces several improvements and bug fixes to the `lumibot` package, primarily focusing on error handling, order processing, and synchronization between Lumibot and brokers. The most important changes include the addition of a consolidated error class for broker API errors, enhancements to order processing logic, and updates to handle OCO (One Cancels the Other) orders more effectively.
* Added `LumibotBrokerAPIError` class to consolidate errors from different brokers into a single class. (`lumibot/brokers/broker.py`)
* Updated imports to include `LumibotBrokerAPIError` in relevant broker files. (`lumibot/brokers/__init__.py`, `lumibot/brokers/tradier.py`) [[1]](diffhunk://#diff-e03f6832dce3e7ac471c69eaded2f026449dae75cf8b3c1bb1407c36cec37ea2L2-R2) …
=> Tradier live updates

lumibot/credentials.py, lumibot/data_sources/data_source_backtesting.py, lumibot/strategies/_strategy.py, lumibot/tools/helpers.py
Introduce functionality to log backtest progress to a CSV file, allowing for better tracking and analysis of backtest performance over time. This includes the ability to specify a custom file path and control logging via an environment variable.
Add functionality to log backtest progress to a CSV file by introducing a flag (`LOG_BACKTEST_PROGRESS_TO_FILE`) and modifying backtest data source classes.
The ability to log backtest progress to a file enhances monitoring and analysis by providing a persistent and detailed record of the backtest execution, including percentage completion and portfolio value. This approach uses an environment variable for toggling and parameterizes file path, ensuring flexibility and ease of use without altering existing functionalities.
> Is this description …
=> Add logging for backtest progress to CSV file

lumibot/backtesting/__init__.py, lumibot/backtesting/interactive_brokers_rest_backtesting.py, lumibot/credentials.py, lumibot/data_sources/data_source.py, lumibot/data_sources/data_source_backtesting.py, lumibot/data_sources/example_broker_data.py, lumibot/data_sources/interactive_brokers_rest_data.py, lumibot/data_sources/schwab_data.py, lumibot/data_sources/tradier_data.py, lumibot/entities/asset.py, lumibot/strategies/_strategy.py, setup.py
Add a backtesting capability for Interactive Brokers REST API to the Lumibot project and integrate it with various system components.
This change is being made to extend the backtesting framework with support for Interactive Brokers REST API, allowing users to simulate trading strategies using historical data from Interactive Brokers while maintaining compatibility with live trading setups. This is necessary to provide a consistent testing environment and to utilize the data offerings of Interactive Brokers in strategy development.
=> ib backtesting working

tests/test_integration_tests.py
Add a new integration test for Yahoo data to the test suite.
This change ensures that key functionality related to Yahoo data integration remains unbroken across updates, providing confidence that users relying on this feature experience consistent behavior. The integration test specifically simulates a backtesting scenario with defined parameters and validates results, which aids in detecting regression and assuring code reliability.
=> added a yahoo integration test

lumibot/tools/indicators.py
Enhance CSV export functionality in the `indicators.py` module to include both chart markers and lines, sorted by datetime and labeled with a type identifier.
The previous implementation only exported chart markers to CSV without sorting or differentiating between types. By combining both markers and lines, adding a type identifier, and sorting by datetime, users can now obtain a more comprehensive and organized dataset from the generated charts.
=> added lines to indicators csv

lumibot/brokers/alpaca.py, lumibot/brokers/broker.py, lumibot/data_sources/alpaca_data.py, lumibot/tools/alpaca_helpers.py
Introduce functionality to fetch and handle option prices from Alpaca, including improved error handling and data validation for option fields.
Implement support for multi-leg options orders in the Alpaca broker interface and enhance quote retrieval functionality for stocks, options, and cryptocurrencies.
Alpaca users previously lacked the ability to submit multi-leg options orders directly through the interface, which limits flexibility and trading strategies; implementing this support resolves that gap. Improvements in the quote retrieval process ensure more accurate and comprehensive data for decision-making across different asset types.
=> Implement preliminary Alpaca options support

.github/workflows/cicd.yaml, README.md
Modify the GitHub Actions workflow to output the HTML coverage report to the "Lumibot" folder, update the coverage badge logic for the "badge" branch, and adjust the README.md coverage badge URL.
These changes ensure the HTML coverage report is stored in the correct folder for accessibility and the coverage badge is correctly committed to and reflected on the "badge" branch, which improves the consistency and accuracy of continuous integration details in the repository documentation.
=> badge fixes

lumibot/data_sources/interactive_brokers_rest_data.py
1. "&" added to the history URL before start date parameter
2. _get_futures_conid() & get_historical_prices needed IF statement updates to check for CONT_FUTURE assets and not just FUTURE
3. Start time for IB needs to be in UTC so updated get_historical_prices() to convert.
Fix the handling of futures and continuous futures data in `interactive_brokers_rest_data.py` by updating the asset type checks, incorporating UTC timezone for timestamps, and correcting a URL formatting issue.
There were bugs in how futures and continuous futures were identified and queried, particularly regarding their expiration checks, which led to incorrect data retrieval. Moreover, timestamps were not properly formatted to reflect UTC time, causing potential discrepancies. Additionally, there was a missing …
=> IB historical futures data bug fixes.

lumibot/tools/helpers.py, lumibot/tools/indicators.py, lumibot/tools/yahoo_helper.py
Enable charts and CSV files to be generated even when no trades have occurred by creating empty CSV files with predefined columns and ensuring plot data has consistent columns.
This change improves the usability of the tool by consistently generating output files even when there are no trades, which helps in maintaining the workflow and processing results seamlessly. Additionally, proxy settings for Yahoo data have been centralized and configured based on availability to ensure robustness during data fetching, enhancing the overall reliability of the system.
=> Charts get generated even when no trades happened now

.github/workflows/cicd.yaml
Remove the `cp coverage.svg .` line from the CI/CD workflow configuration in `cicd.yaml`.
The file copy command `cp coverage.svg .` is unnecessary as it does not affect the badge generation process and was likely leading to errors or redundant steps in the workflow. Removing this line streamlines the CI/CD process for updating the test coverage badge.
=> Attempting to fix the badge for test coverage

lumibot/brokers/alpaca.py, lumibot/brokers/tradier.py, lumibot/components/options_helper.py, lumibot/strategies/strategy_executor.py, requirements.txt, setup.py
Correct the handling of multi-leg order types in Alpaca and Tradier brokers, improve options support by mapping order types to Lumi types, and add logic to determine order type based on price; introduce a new "T" unit for flexible sleeptimes in strategy scheduling; and update LumiBot package version to 3.13.8.
To fix a bug in handling "even" order types in Alpaca and Tradier which were previously unhandled, and ensure consistent interpretation of order types in LumiBot; improve scheduling precision by introducing a new "T" time unit to the sleeptime options; and ensure versioning reflects these changes for proper package management and deployment.
=> Bug fixes for options

.github/workflows/cicd.yaml, coverage.svg
Modify the CI/CD workflow to check for an existing 'badge' branch or create a new orphan 'badge' branch to ensure the coverage badge updates correctly.
The existing workflow attempted to fetch and check out the 'badge' branch without checking if it existed, leading to potential errors. By implementing logic to create an orphan branch if 'badge' doesn't exist, we ensure that the coverage badge can be generated and updated consistently. This approach addresses the issue encountered with badge generation in CI/CD processes.
=> attempt to get badge to work

README.md
Update the CI status badge URL in the README file to point to the correct workflow file.
The previous URL linked to an incorrect workflow file, causing the status badge to not display the correct build status. This change corrects the file path to ensure accurate status reporting for the repository.
=> attempt to fix status badge

README.md
Update the coverage badge link in the README.md file to point to the CI/CD workflow page.
The previous link to the coverage report preview page was broken, so it is being redirected to the CI/CD workflow page for accessibility until a more detailed report location can be addressed. This provides immediate and functional feedback about the test coverage status.
=> attempt to fix coverage icon

lumibot/__init__.py, lumibot/brokers/broker.py, lumibot/constants.py, lumibot/tools/ccxt_data_store.py, lumibot/tools/helpers.py, lumibot/tools/indicators.py, lumibot/tools/yahoo_helper.py, setup.py, tests/backtest/test_dividends.py
Separate constants into a new module, update module imports, increment version, and add comprehensive dividend handling tests.
By segregating constants into a dedicated module, we avoid circular dependencies and enhance code clarity and maintainability. The imports are adjusted accordingly across the codebase to reflect this organization. The version increment reflects these structural changes. The addition of dividend handling tests aims to validate and ensure robust handling of dividends in the Lumibot, covering both Yahoo Finance and Polygon data sources.
=> added tests and bug fixes

lumibot/data_sources/alpaca_data.py, lumibot/tools/helpers.py, tests/test_alpaca_data.py, tests/test_helpers.py
Add an auto-adjust functionality to the Alpaca data source for split and dividend adjustments, introduce a helper function to check if a market is open, and enhance unit tests to cover new functionalities.
The auto-adjust feature allows users to choose between raw and adjusted data, addressing how data is processed post-splits and dividends, enhancing data handling flexibility. The `is_market_open` function is introduced to improve the usability and robustness of market data requests, accompanied by comprehensive testing to ensure accuracy and stability in diverse scenarios.
=> Be alpaca data auto adjust

lumibot/backtesting/polygon_backtesting.py, lumibot/credentials.py, lumibot/data_sources/pandas_data.py, lumibot/data_sources/yahoo_data.py, lumibot/strategies/_strategy.py, lumibot/tools/__init__.py, lumibot/tools/error_logger.py, lumibot/tools/polygon_helper.py, tests/test_alpaca_backtesting.py, tests/test_error_logger.py, tests/test_yahoo_data.py
Enhance handling of index assets by providing specific error messages for NaN prices and missing data, introduce a new method to format index symbols for Yahoo Finance, and add corresponding test cases for index symbol formatting and data retrieval.
Recent issues were encountered with data access for index assets leading to unclear error messages, typically due to missing data or constraints with current data providers. By detailing these messages, users can make informed decisions about alternative data sources like Yahoo Finance. Additionally, formatted index symbols in alignment with Yahoo Finance's expectations improve data retrieval accuracy, and the accompanying tests ensure robustness and correctness.
> Is this description stale? Ask me to generate a new description by commenting …
=> Index-fixes

lumibot/brokers/alpaca.py, lumibot/entities/order.py, lumibot/strategies/_strategy.py, setup.py, tests/test_alpaca.py, tests/test_strategy_methods.py
Add error handling for None quantity orders in Alpaca broker and strategy validation, and implement corresponding unit tests to ensure correct order processing behavior.
These changes are made to prevent invalid order submissions by checking for None quantities, thereby improving robustness and preventing potential exceptions during order processing. The addition of unit tests ensures that these scenarios are thoroughly tested and handled appropriately.
=> added tests and qty error checking

docsrc/brokers.projectx.rst, docsrc/deployment.rst, lumibot/brokers/projectx.py, lumibot/credentials.py, lumibot/data_sources/projectx_data.py, setup.py, tests/test_projectx_url_mappings.py
Add detailed documentation for ProjectX setup with unique environment variables for each broker and streamline ProjectX environment variables handling for multiple firms integration.
The updated documentation and code facilitate easier configuration and integration of ProjectX with various futures trading brokers by using specified environment variables, thereby reducing user errors and enhancing clarity on broker requirements. The change also includes URL mapping for brokers to improve automatic configuration detection and management.
=> added project x docs and simplified the env vars for project x

lumibot/brokers/alpaca.py, lumibot/brokers/tradier.py, tests/test_alpaca.py
=> Be fix sync orders

lumibot/backtesting/alpaca_backtesting.py, lumibot/data_sources/alpaca_data.py, lumibot/data_sources/bitunix_data.py, lumibot/data_sources/data_source.py, lumibot/data_sources/data_source_backtesting.py, lumibot/data_sources/tradier_data.py, lumibot/example_strategies/schedule_function.py, lumibot/strategies/strategy.py, tests/test_alpaca_backtesting.py, tests/test_alpaca_data.py, tests/test_strategy_methods.py, tests/test_tradier_data.py, tests/test_yahoo_data.py
Update the codebase by renaming all instances of `self._tzinfo` to `self.tzinfo`, and introduce a new feature for scheduling functions using `register_cron_callback` in the Strategy class.
The refactor from `self._tzinfo` to `self.tzinfo` improves code readability and consistency across the codebase related to timezone handling, eliminating the need for a leading underscore typically used for private variables. The new cron scheduling feature allows users to schedule functions at specific times, enhancing strategy automation capabilities. This feature was implemented with consideration for live trading environments while ensuring it does not affect backtesting.
=> scheduled functions

test_quiet_logs_simple.py
Remove hardcoded absolute path from `test_quiet_logs_simple.py` because it caused test failures on other systems.
Remove the hardcoded path insertion from `test_quiet_logs_simple.py`.
The hardcoded path was specific to a single developer's environment and could cause errors or confusion for other developers running the tests; removing it improves portability and maintainability of the test script. This change ensures that the code is cleaner and does not rely on environment-specific configurations.
=> Remove hardcoded path from test file

lumibot/data_sources/alpaca_data.py, lumibot/data_sources/data_source.py, lumibot/data_sources/projectx_data.py, lumibot/strategies/strategy.py, setup.py
Optimize the `get_bars` function for Alpaca in `alpaca_data.py` to support efficient multi-symbol fetching, reducing HTTP overhead by batching requests per asset class and introducing a `sleep_time` parameter for rate limiting.
The previous implementation fetched bars individually for each symbol, resulting in significant overhead and slower performance due to repeated HTTP requests and potential rate limiting. This new approach batches symbols per asset class and efficiently processes them with reduced API calls, thereby significantly increasing the speed of fetching bars from Alpaca, meeting a performance need in high-traffic scenarios. Additionally, `sleep_time` is introduced to allow adjustable rate-limiting across different methods, accommodating flexibility in data fetching …
=> Increased the speed of get bars for alpaca

lumibot/brokers/broker.py, lumibot/brokers/projectx.py, lumibot/brokers/tradovate.py, lumibot/credentials.py, lumibot/data_sources/databento_data_polars.py, lumibot/entities/bars.py, lumibot/entities/order.py, lumibot/strategies/strategy_executor.py, lumibot/tools/databento_helper_polars.py, setup.py, tests/test_databento_live.py, tests/test_databento_timezone_fixes.py, tests/test_projectx.py, tests/test_projectx_lifecycle.py, tests/test_projectx_lifecycle_unit.py, tests/test_projectx_url_mappings.py
Refactor the `lumibot` project codebase to improve handling of futures and implement a more robust Live API integration with DataBento for enhanced data retrieval capabilities, switch to a cleaner central lifecycle management, introduce exponential backoff for API rate limiting, and modify logging levels for better clarity.
The changes address bugs associated with futures data processing, optimize API interactions by adjusting to rate limits more effectively, and ensure the lifecycle is maintained centrally to enhance clarity and maintainability. The integration of DataBento's Live API aims to substantially improve data retrieval latency, bringing it under 1 minute, which is critical for real-time trading strategies. This refactoring also seeks to streamline logging outputs and error …
=> Futures bug fixes

lumibot/entities/asset.py, lumibot/strategies/strategy.py, lumibot/tools/futures_symbols.py, setup.py, tests/test_continuous_futures.py, tests/test_futures_integration.py, tests/test_logger_env_vars.py
Revise the continuous futures position handling mechanism in the Lumibot framework to include new contract generation formats and implement robust matching logic for identifying the best active contract positions, along with corresponding test additions.
The current system faced difficulties properly identifying and matching continuous futures positions due to limited contract formats. This update ensures accurate detection and prioritization of continuous futures by incorporating new formats (e.g., single-digit year, dot notation) and developing a more comprehensive matching strategy as outlined in the new `futures_symbols.py` utility. This robust approach resolves previous issues by analyzing every contract variation and ranking by priority, improving the reliability of the trading …
=> fixed continuous futures get position bug

lumibot/brokers/projectx.py, lumibot/components/vix_helper.py, lumibot/data_sources/databento_data_polars.py, lumibot/strategies/strategy_executor.py, lumibot/tools/databento_helper_polars.py, lumibot/tools/projectx_helpers.py, requirements.txt, requirements_dev.txt, setup.py, tests/test_databento_live.py, tests/test_projectx.py, tests/test_projectx_lifecycle_unit.py, tests/test_vix_helper.py
Fix the DataBento data source for live data streaming by enhancing live streaming components, correcting API integrations, and improving data handling; ensure proper price conversion and aggregation of real-time market data, and add comprehensive tests for extended period handling.
The changes address issues with DataBento's live data handling, resolve integrations with its live API, optimize trade data processing, and improve bar finalization to ensure correctly formatted minute-level market data with minimal lag. This ensures more reliable data streaming and accurate real-time analytics, particularly for trading systems using long data intervals. The added test for long time periods ensures robustness against performance degradation in scenarios involving large data sets.
> Is this …
=> data bento bug fixed for live data
